"""Durable task runtime for Veoveo Python MCP servers.

SurrealDB is the sole task authority; the platform-store migrations owned by
the Rust workspace define the schema this package reads and writes.
"""

from .runtime import TaskRuntime
from .store import OutboxEvent, OutboxWake, StoreError, SurrealStore, outbox_draft
from .types import (
    ClaimedTask,
    Conflict,
    CreateTask,
    CreateTaskResult,
    DuplicateInputKey,
    InvalidInputKey,
    InvalidProgress,
    InvalidRecord,
    InvalidTransition,
    LeaseHeld,
    PrincipalKind,
    RecoveryClass,
    RecoveryReport,
    TaskError,
    TaskFailure,
    TaskInputExchange,
    TaskInputRequest,
    TaskInputSubmission,
    TaskNotFound,
    TaskOwner,
    TaskSnapshot,
    TaskStatus,
    TaskTransition,
    TaskUpdate,
    TaskUpdateCursor,
    WrongServer,
    allowed_transition,
    new_task_id,
    parse_task_id,
    validate_retention_pin,
)

__all__ = [
    "TaskRuntime",
    "OutboxEvent",
    "OutboxWake",
    "StoreError",
    "SurrealStore",
    "outbox_draft",
    "ClaimedTask",
    "Conflict",
    "CreateTask",
    "CreateTaskResult",
    "DuplicateInputKey",
    "InvalidInputKey",
    "InvalidProgress",
    "InvalidRecord",
    "InvalidTransition",
    "LeaseHeld",
    "PrincipalKind",
    "RecoveryClass",
    "RecoveryReport",
    "TaskError",
    "TaskFailure",
    "TaskInputExchange",
    "TaskInputRequest",
    "TaskInputSubmission",
    "TaskNotFound",
    "TaskOwner",
    "TaskSnapshot",
    "TaskStatus",
    "TaskTransition",
    "TaskUpdate",
    "TaskUpdateCursor",
    "WrongServer",
    "allowed_transition",
    "new_task_id",
    "parse_task_id",
    "validate_retention_pin",
]
