import {toolEnvelope,successfulToolEnvelope} from "../../../mcp/apps-extension/browser/admission.js";
const pending=new Map(),listeners=new Map();let nextId=1,rendered=null,compiled=null,activeTab="preview",validateTimer;
const el=id=>document.getElementById(id);
const bridge={post(message){parent.postMessage(message,"*")},request(method,params){const id=nextId++;this.post({jsonrpc:"2.0",id,method,params});return new Promise((resolve,reject)=>pending.set(id,{resolve,reject}))},notify(method,params){this.post({jsonrpc:"2.0",method,params})},on(method,handler){listeners.set(method,handler)}};
addEventListener("message",event=>{if(event.source!==parent||!event.data||event.data.jsonrpc!=="2.0")return;const message=event.data;if(message.id!==undefined&&pending.has(message.id)){const entry=pending.get(message.id);pending.delete(message.id);message.error?entry.reject(new Error(message.error.message||"The chart host didn't complete that request. Try again.")):entry.resolve(message.result);return}if(message.method)listeners.get(message.method)?.(message.params,message.id)});
function setStatus(text,kind=""){el("status").textContent=text;el("status").className=`status ${kind}`.trim()}
function setMessage(text,kind=""){el("message").textContent=text;el("message").className=`message ${kind}`.trim()}
function chartEnvelope(value){if(value&&["structured_content","is_error"].some(key=>Object.hasOwn(value,key)))throw new Error("Unsupported Chart tool result spelling");return toolEnvelope(value)}
function structured(result){return result?.structuredContent??result}
function errorText(result,name){const item=(result?.content||[]).find(entry=>entry?.type==="text"&&typeof entry.text==="string");return item?.text||`${name} failed`}
async function tool(name,args){const result=chartEnvelope(await bridge.request("tools/call",{name,arguments:args}));if(result?.isError)throw new Error(errorText(result,name));return result}
function applyTheme(context){const theme=context?.theme;if(theme==="dark"||theme==="light")document.documentElement.dataset.theme=theme}
function parseRows(){const rows=JSON.parse(el("data").value);if(!Array.isArray(rows)||rows.length===0)throw new Error("Inline data must be a non-empty JSON array.");if(rows.length>5000)throw new Error("Composer drafts are limited to 5,000 inline rows.");if(!rows.every(row=>row&&typeof row==="object"&&!Array.isArray(row)))throw new Error("Every data row must be a JSON object.");return rows}
function columns(rows){return [...new Set(rows.flatMap(row=>Object.keys(row)))].sort()}
function syncFields(){try{const rows=parseRows(),names=columns(rows);for(const [id,preferred] of [["x-field","region"],["y-field","revenue"]]){const select=el(id),current=select.value||preferred;select.replaceChildren(...names.map(name=>{const option=document.createElement("option");option.value=name;option.textContent=name;return option}));select.value=names.includes(current)?current:names[id==="x-field"?0:Math.min(1,names.length-1)]||""}}catch{}}
function input(){const rows=parseRows(),x=el("x-field").value,y=el("y-field").value;if(!x||!y)throw new Error("Choose both X and Y fields.");const semantic={};for(const field of columns(rows)){const sample=rows.find(row=>row[field]!==null&&row[field]!==undefined)?.[field];semantic[field]=typeof sample==="number"?"Quantity":"Category"}const chart_spec={chartType:el("chart-type").value,encodings:{x:{field:x},y:{field:y}},baseSize:{width:Number(el("width").value),height:Number(el("height").value)}};if(el("title").value.trim())chart_spec.title=el("title").value.trim();if(el("subtitle").value.trim())chart_spec.subtitle=el("subtitle").value.trim();const value={data:{values:rows},semantic_types:semantic,chart_spec};if(el("theme").value)value.theme_spec=el("theme").value;return value}
function applyInput(value){if(!value?.chart_spec||!Array.isArray(value?.data?.values))return;el("data").value=JSON.stringify(value.data.values,null,2);el("title").value=value.chart_spec.title||"";el("subtitle").value=value.chart_spec.subtitle||"";el("width").value=value.chart_spec.baseSize?.width||640;el("height").value=value.chart_spec.baseSize?.height||380;if(value.theme_spec&&typeof value.theme_spec==="string")el("theme").value=value.theme_spec;syncFields();const enc=value.chart_spec.encodings||{};if(enc.x?.field)el("x-field").value=enc.x.field;if(enc.y?.field)el("y-field").value=enc.y.field;if(value.chart_spec.chartType)el("chart-type").value=value.chart_spec.chartType;void render()}
function show(){const canvas=el("canvas");canvas.replaceChildren();el("preview-tab").classList.toggle("active",activeTab==="preview");el("compiled-tab").classList.toggle("active",activeTab==="compiled");if(activeTab==="compiled"){const pre=document.createElement("pre");pre.className="diagnostics";pre.textContent=compiled?JSON.stringify(compiled,null,2):"Compile the current draft to inspect its backend-native specification.";canvas.append(pre);return}if(!rendered){const empty=document.createElement("div");empty.className="empty";empty.textContent="Render the current draft to create a chart preview.";canvas.append(empty);return}const image=document.createElement("img");image.alt=el("title").value.trim()||"Rendered chart";image.src=rendered.url;canvas.append(image)}
async function validate(silent=false){clearTimeout(validateTimer);try{const value=input(),backend=el("backend").value;setStatus("validating");const result=structured(await tool("validate_chart",{...value,backend}));if(result.valid){setStatus("valid","good");if(!silent)setMessage(`${backend} accepts ${result.chartType}.`,"good")}else{const errors=(result.errors||[]).map(item=>item.message).join("; ")||"Chart input is invalid.";setStatus("invalid","bad");setMessage(errors,"bad")}return result}catch(error){setStatus("invalid","bad");setMessage(error.message,"bad");if(!silent)throw error}}
async function compile(){const value=input(),backend=el("backend").value;const result=structured(await tool("compile_chart",{...value,backend}));compiled=result;return result}
async function render(){const button=el("render");button.disabled=true;try{const value=input(),backend=el("backend").value;setStatus("rendering");const result=await tool("render_chart",{...value,backend,format:backend==="chartjs"?"png":"svg",scale:1});const image=(result.content||[]).find(item=>item?.type==="image");const svg=(result.content||[]).find(item=>item?.type==="text"&&typeof item.text==="string"&&item.text.trim().startsWith("<svg"));if(image)rendered={url:`data:${image.mimeType};base64,${image.data}`,copy:image.data,mime:image.mimeType};else if(svg)rendered={url:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg.text)}`,copy:svg.text,mime:"image/svg+xml"};else throw new Error("The renderer returned no image output.");await compile();activeTab="preview";show();el("copy-output").disabled=false;setStatus("rendered","good");setMessage(`${backend} rendered the current draft.`,"good")}catch(error){setStatus("failed","bad");setMessage(error.message,"bad")}finally{button.disabled=false;reportSize()}}
async function copyText(text,label){try{await navigator.clipboard.writeText(text);setMessage(`${label} copied.`,"good")}catch{const area=document.createElement("textarea");area.value=text;document.body.append(area);area.select();document.execCommand("copy");area.remove();setMessage(`${label} copied.`,"good")}}
function reportSize(){bridge.notify("ui/notifications/size-changed",{height:Math.ceil(document.documentElement.getBoundingClientRect().height)})}
async function loadCatalog(){const backend=el("backend").value;const [typesResult,themesResult]=await Promise.all([tool("list_chart_types",{backend}),tool("list_themes",{})]);const types=structured(typesResult)?.backends?.[0]?.chartTypes||[];const current=el("chart-type").value;el("chart-type").replaceChildren(...types.map(item=>{const option=document.createElement("option");option.value=item.chartType;option.textContent=item.chartType;return option}));if(types.some(item=>item.chartType===current))el("chart-type").value=current;else if(types.some(item=>item.chartType==="Bar Chart"))el("chart-type").value="Bar Chart";const themes=structured(themesResult)?.themes||[];const prior=el("theme").value;el("theme").replaceChildren(new Option("Default",""),...themes.map(item=>new Option(item.label||item.name||item.id,item.id||item.name)));el("theme").value=prior}
bridge.on("ui/notifications/host-context-changed",params=>applyTheme(params?.hostContext||params));bridge.on("ui/notifications/tool-input",params=>{if(params?.arguments)applyInput(params.arguments)});bridge.on("ui/notifications/tool-result",params=>{const value=structured(successfulToolEnvelope(chartEnvelope(params?.result||params)))?.input;if(value)applyInput(value)});bridge.on("ui/resource-teardown",(_params,id)=>{clearTimeout(validateTimer);if(id!==undefined)bridge.post({jsonrpc:"2.0",id,result:{}})});
el("editor").addEventListener("submit",event=>{event.preventDefault();void render()});el("validate").addEventListener("click",()=>void validate());el("format-data").addEventListener("click",()=>{try{el("data").value=JSON.stringify(parseRows(),null,2);syncFields();setMessage("Inline data formatted.","good")}catch(error){setMessage(error.message,"bad")}});el("copy-spec").addEventListener("click",()=>{try{void copyText(JSON.stringify(input(),null,2),"Chart input")}catch(error){setMessage(error.message,"bad")}});el("copy-output").addEventListener("click",()=>{if(rendered)void copyText(rendered.copy,rendered.mime==="image/svg+xml"?"SVG":"PNG base64")});el("preview-tab").addEventListener("click",()=>{activeTab="preview";show()});el("compiled-tab").addEventListener("click",async()=>{activeTab="compiled";try{await compile()}catch(error){compiled={error:error.message}}show()});el("backend").addEventListener("change",async()=>{try{await loadCatalog();await validate(true)}catch(error){setMessage(error.message,"bad")}});el("data").addEventListener("input",syncFields);for(const node of document.querySelectorAll("input,select,textarea"))node.addEventListener("input",()=>{clearTimeout(validateTimer);validateTimer=setTimeout(()=>void validate(true),550)});
(async()=>{try{const initialized=await bridge.request("ui/initialize",{protocolVersion:"2026-01-26",appInfo:{name:"charts-composer",version:"1.0.0"},appCapabilities:{availableDisplayModes:["inline"]}});bridge.notify("ui/notifications/initialized",{});applyTheme(initialized?.hostContext);syncFields();await loadCatalog();setStatus("ready","good");await render()}catch(error){setStatus("unavailable","bad");setMessage(`The composer couldn't start. Reload to try again. (${error.message})`,"bad");show()}finally{reportSize()}})();
