[worker.oci]
  gc = true

[[worker.oci.gcpolicy]]
  filters = ["type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
  keepDuration = "168h"
  reservedSpace = "240GB"
  maxUsedSpace = "320GB"
  minFreeSpace = "80GB"

[[worker.oci.gcpolicy]]
  all = true
  reservedSpace = "240GB"
  maxUsedSpace = "320GB"
  minFreeSpace = "80GB"
