import {H264DecoderAdmission} from "./h264.js";
import {element as $} from "./dom.js";
import {resourceJson, structuredResult, toolEnvelope, taskEnvelope} from "../../../mcp/apps-extension/browser/admission.js";
import {admit, resourceValue, toolValue} from "./contracts.js";
"use strict";
const STREAM_PROTOCOL="veoveo.h264.annexb.v1",bridge=(()=>{let id=1;const waiting=new Map(),handlers=new Map();const post=m=>parent.postMessage(m,"*");addEventListener("message",event=>{if(event.source!==parent)return;const m=event.data;if(!m||m.jsonrpc!=="2.0")return;if(m.id!==undefined&&(m.result!==undefined||m.error!==undefined)){const w=waiting.get(m.id);if(!w)return;waiting.delete(m.id);m.error?w.reject(new Error(m.error.message||"host error")):w.resolve(m.result);return;}const h=handlers.get(m.method);if(h)h(m.params,m.id);else if(m.id!==undefined)post({jsonrpc:"2.0",id:m.id,error:{code:-32601,message:"method not found"}});});return{request:(method,params)=>new Promise((resolve,reject)=>{const requestId=id++;waiting.set(requestId,{resolve,reject});post({jsonrpc:"2.0",id:requestId,method,params});}),notify:(method,params)=>post({jsonrpc:"2.0",method,params}),on:(method,handler)=>handlers.set(method,handler),post};})();
const MAX_RECOVERY_BACKOFF_ATTEMPT=8,viewerInstanceId=crypto.randomUUID(),selected=new Set(),views=new Map(),players=new Map(),recoveries=new Map();let sessionId=null,cameras=/** @type {import("./generated/uav-sim").AppContracts["cameras"]} */ ([]),closing=false,lastHeight=0,subscribedUri=null,decodeLabel=null;
function uuidV7(){const bytes=crypto.getRandomValues(new Uint8Array(16));let timestamp=BigInt(Date.now());for(let index=5;index>=0;index-=1){bytes[index]=Number(timestamp&255n);timestamp>>=8n;}bytes[6]=(bytes[6]&15)|112;bytes[8]=(bytes[8]&63)|128;const hex=Array.from(bytes,value=>value.toString(16).padStart(2,"0")).join("");return`${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;}
function configureAgents(initialized){const targets=initialized?.hostContext?._meta?.["ai.veoveo/agent-message-targets"];$('agent').replaceChildren();if(!Array.isArray(targets)||!targets.length)return;for(const target of targets){if(typeof target!=="string")continue;const option=document.createElement("option");option.value=target;option.textContent=target;$('agent').append(option);}if($('agent').options.length)$('commands').classList.add('available');reportSize();}
async function sendInstruction(event){event.preventDefault();const agentId=$('agent').value,message=$('command').value.trim();if(!agentId||!message)return;$('command-result').textContent="Sending…";try{await bridge.request("veoveo/agents/message",{agentId,requestId:uuidV7(),message});$('command').value="";$('command-result').textContent=`Instruction queued for ${agentId}.`;}catch(cause){$('command-result').textContent=String(cause?.message||cause).slice(0,200);}}
$('commands').addEventListener('submit',sendInstruction);
const fixedFps=value=>String(Math.max(0,Math.round(value))).padStart(2,"0");
/** @template {keyof typeof import("./contracts.js").tools} N @param {N} name @param {Record<string,unknown>} args @returns {Promise<import("./generated/uav-sim").AppContracts[(typeof import("./contracts.js").tools)[N]]>} */
async function call(name,args){if(name==="open_live_view")await ensureSubscription();return toolValue(name,structuredResult(await bridge.request("tools/call",{name,arguments:args})),args);}
/** @template {keyof import("./generated/uav-sim").AppContracts} K @param {string} uri @param {K} root @returns {Promise<import("./generated/uav-sim").AppContracts[K]>} */
async function read(uri,root){return resourceValue(uri,resourceJson(await bridge.request("resources/read",{uri}),uri),root);}
function error(cause){$("error").textContent=String(cause?.message||cause).replace(/Bearer\s+\S+/gi,"Bearer [redacted]").slice(0,300);$("error").hidden=false;}
function clearError(){$("error").hidden=true;$("error").textContent="";}
function status(){$("count").textContent=`${views.size} view${views.size===1?"":"s"}`;$("status").textContent=recoveries.size?"reconnecting":(views.size?"live":"ready");$("status").classList.toggle("live",views.size>0&&!recoveries.size);}
function reportSize(){requestAnimationFrame(()=>{const height=Math.ceil(document.documentElement.scrollHeight);if(Math.abs(height-lastHeight)<2)return;lastHeight=height;bridge.notify("ui/notifications/size-changed",{height});});}
async function decoderConfig(stream,codec){if(typeof VideoDecoder==="undefined"||!navigator.mediaCapabilities?.decodingInfo)throw new Error("This browser can't decode H.264 video with WebCodecs. Use a current Chrome, Edge, or Safari with hardware acceleration turned on.");const media=await navigator.mediaCapabilities.decodingInfo({type:"file",video:{contentType:`video/mp4; codecs="${codec}"`,width:stream.codedWidthPx,height:stream.codedHeightPx,bitrate:12000000,framerate:stream.frameRateMillihertz/1000}});if(!media.supported||!media.smooth)throw new Error("This browser can't play this camera's H.264 video smoothly. Turn on hardware acceleration in your browser settings and reload.");const base={codec:codec,codedWidth:stream.codedWidthPx,codedHeight:stream.codedHeightPx,optimizeForLatency:true};let config=/** @type {VideoDecoderConfig} */ ({...base,hardwareAcceleration:"prefer-hardware"}),support=await VideoDecoder.isConfigSupported(config);if(!support.supported){config={...base,hardwareAcceleration:"no-preference"};support=await VideoDecoder.isConfigSupported(config);}if(!support.supported)throw new Error(`H.264 ${codec} is unavailable`);const label=media.powerEfficient?"NVIDIA NVENC · hardware H.264 decode":"NVIDIA NVENC · software H.264 decode";return {config,label};}
function smoothing(camera){const value=camera.rig?.smoothing;return value?`smooth T${value.translationHalfLifeMs}/R${value.rotationHalfLifeMs} ms`:"exact pose";}
function node(camera){const section=document.createElement("section");section.className="view";section.id=`view-${camera.cameraId}`;section.innerHTML=`<canvas id="video-${camera.cameraId}" aria-label="${camera.cameraId} live video"></canvas><div class="empty">Opening camera…</div><div class="bar"><span>${camera.cameraId}</span><span class="health">${camera.health}</span><span>${smoothing(camera)}</span><button type="button">Close</button></div><div class="stats"><span class="requested">source ${camera.widthPx}×${camera.heightPx} · ${fixedFps(camera.frameRateMillihertz/1000)} fps</span><span class="decoded">video pending</span><span class="age">age pending</span><span class="transport">H.264 starting</span><span class="encoder">NVENC</span></div>`;section.querySelector("button").onclick=()=>{selected.delete(camera.cameraId);void close(camera.cameraId,true);renderChoices();};$("grid").append(section);return section;}
function identify(section,stream){const region=stream.sourceRegion;section.dataset.viewerInstanceId=viewerInstanceId;section.dataset.liveViewId=stream.liveViewId;section.dataset.streamProductId=stream.streamProductId;section.dataset.codedWidth=String(stream.codedWidthPx);section.dataset.codedHeight=String(stream.codedHeightPx);section.dataset.crop=`${region.xPx},${region.yPx},${region.widthPx},${region.heightPx}`;}
function attachView(player,view,stream){const {camera,section}=view,canvas=section.querySelector("canvas"),context=canvas.getContext("2d",{alpha:false});if(!context)throw new Error("This browser couldn't create a video canvas. Reload the app.");canvas.width=stream.widthPx;canvas.height=stream.heightPx;canvas.dataset.codec=player.admission?.codec??"pending";canvas.dataset.sourceWidth=String(stream.codedWidthPx);canvas.dataset.sourceHeight=String(stream.codedHeightPx);canvas.dataset.frameRate=String(stream.frameRateMillihertz/1000);canvas.dataset.decodedFrames="0";canvas.dataset.droppedFrames="0";canvas.dataset.mediaTimeSeconds="0";canvas.dataset.receiveToDisplayMs="0";view.context=context;view.region=stream.sourceRegion;view.productId=stream.streamProductId;player.views.set(camera.cameraId,view);identify(section,{...stream,liveViewId:player.connection.stream.liveViewId});section.querySelector(".health").textContent=stream.cameraHealth;section.querySelector(".transport").textContent=player.socket?"tiled H.264 connected":"tiled H.264 starting";}
function configureDecoder(player,stream,config){player.decoder=new VideoDecoder({output:frame=>{try{if(players.get(stream.streamProductId)!==player)return;const now=performance.now(),receiveToDisplayMs=Math.max(0,now-player.lastReceivedAt);player.decodedFrames+=1;player.presentedAt.push(now);while(player.presentedAt.length&&now-player.presentedAt[0]>1000)player.presentedAt.shift();for(const view of player.views.values()){const {camera,section,context,region}=view,canvas=section.querySelector("canvas");context.drawImage(frame,region.xPx,region.yPx,region.widthPx,region.heightPx,0,0,canvas.width,canvas.height);canvas.dataset.decodedFrames=String(player.decodedFrames);canvas.dataset.lastFrameAt=String(now);canvas.dataset.mediaTimeSeconds=String(frame.timestamp/1000000);canvas.dataset.receiveToDisplayMs=String(receiveToDisplayMs);canvas.dataset.decodeQueueSize=String(player.decoder.decodeQueueSize);section.querySelector(".empty")?.remove();section.querySelector(".health").textContent="live";section.querySelector(".decoded").textContent=`video ${canvas.width}×${canvas.height} · ${fixedFps(player.presentedAt.length)} fps`;section.querySelector(".age").textContent=`age ${Math.round(receiveToDisplayMs)} ms`;section.querySelector(".transport").textContent="tiled H.264 live";cancelRecovery(camera.cameraId);}clearError();}finally{frame.close();}},error:cause=>{if(players.get(stream.streamProductId)===player)void recoverProduct(stream.streamProductId,cause);}});player.decoder.configure(config);for(const view of player.views.values())view.section.querySelector("canvas").dataset.codec=config.codec;}
function connectSocket(player,stream,token){const url=new URL(stream.endpoint.streamUrl);url.searchParams.set("liveViewId",stream.liveViewId);const socket=new WebSocket(url,[STREAM_PROTOCOL,`authorization.bearer.${token}`]);player.socket=socket;socket.binaryType="arraybuffer";socket.onopen=()=>{if(players.get(stream.streamProductId)!==player)return;for(const view of player.views.values())view.section.querySelector(".transport").textContent="tiled H.264 connected";};socket.onmessage=event=>{if(players.get(stream.streamProductId)!==player||!(event.data instanceof ArrayBuffer))return;const bytes=new Uint8Array(event.data);player.lastReceivedAt=performance.now();const timestamp=Math.round(player.chunkSequence*1000000000/stream.frameRateMillihertz);player.chunkSequence+=1;player.admission.push(bytes,timestamp);};socket.onerror=()=>{for(const view of player.views.values())view.section.querySelector(".transport").textContent="video connection lost";};socket.onclose=()=>{if(!closing&&players.get(stream.streamProductId)===player)void recoverProduct(stream.streamProductId,"The camera stream stopped. Reconnecting…");};}
function cancelRecovery(cameraId){const recovery=recoveries.get(cameraId);if(recovery?.timer!=null)clearTimeout(recovery.timer);recoveries.delete(cameraId);status();}
function scheduleRecovery(cameraId,cause){if(closing||!selected.has(cameraId))return;const prior=recoveries.get(cameraId),attempt=(prior?.attempt??0)+1;if(prior?.timer!=null)clearTimeout(prior.timer);const recoveryState={attempt,timer:null};recoveries.set(cameraId,recoveryState);const delay=Math.min(5000,250*2**Math.min(attempt-1,MAX_RECOVERY_BACKOFF_ATTEMPT));error(attempt>MAX_RECOVERY_BACKOFF_ATTEMPT?"Camera recovery is waiting for simulator readiness. Views reopen when the simulator is ready.":cause);recoveryState.timer=setTimeout(()=>{recoveryState.timer=null;if(closing||!selected.has(cameraId)){cancelRecovery(cameraId);return;}const camera=cameras.find(value=>value.cameraId===cameraId);if(camera)void open(camera);},delay);status();}
function retrySelectedNow(){for(const cameraId of selected){const recoveryState=recoveries.get(cameraId);if(!recoveryState)continue;if(recoveryState.timer!==null)clearTimeout(recoveryState.timer);recoveries.delete(cameraId);const camera=cameras.find(value=>value.cameraId===cameraId);if(camera&&!views.has(cameraId))void open(camera);}status();}
async function open(camera){if(views.has(camera.cameraId)||closing)return;$("grid").querySelector(".placeholder")?.remove();const section=node(camera),view={camera,section,context:null,region:null,productId:null};views.set(camera.cameraId,view);status();let connection=null;try{connection=await call("open_live_view",{sessionId,cameraId:camera.cameraId,viewerInstanceId});const stream=connection.stream;if(views.get(camera.cameraId)!==view||!selected.has(camera.cameraId)){await call("close_live_view",{sessionId,liveViewId:stream.liveViewId,viewerInstanceId});return;}let player=players.get(stream.streamProductId);if(player){attachView(player,view,stream);await call("close_live_view",{sessionId,liveViewId:stream.liveViewId,viewerInstanceId});return;}player={connection,socket:null,decoder:null,renew:null,chunkSequence:0,decodedFrames:0,presentedAt:[],lastReceivedAt:0,views:new Map()};players.set(stream.streamProductId,player);attachView(player,view,stream);player.admission=new H264DecoderAdmission({configure:async codec=>{const {config,label}=await decoderConfig(stream,codec);return()=>{if(players.get(stream.streamProductId)===player){decodeLabel=label;$("decode").textContent=label;configureDecoder(player,stream,config);}};},reset:()=>{try{player.decoder?.close();}catch(_){}player.decoder=null;},decode:(bytes,timestamp,isKey)=>{if(player.decoder.decodeQueueSize>=8)throw new Error("H.264 decoder queue exceeded");player.decoder.decode(new EncodedVideoChunk({type:isKey?"key":"delta",timestamp,data:bytes}));},failure:cause=>{if(players.get(stream.streamProductId)===player)void recoverProduct(stream.streamProductId,cause);}});connectSocket(player,stream,connection.accessToken);armRenew(stream.streamProductId);}catch(cause){if(connection&&!players.has(connection.stream.streamProductId)){try{await call("close_live_view",{sessionId,liveViewId:connection.stream.liveViewId,viewerInstanceId});}catch(_){}}await close(camera.cameraId,true,false);scheduleRecovery(camera.cameraId,cause);}}
async function recoverProduct(productId,cause){const player=players.get(productId);if(!player)return;const cameraIds=[...player.views.keys()].filter(cameraId=>selected.has(cameraId));await Promise.all(cameraIds.map(cameraId=>close(cameraId,true,false)));for(const cameraId of cameraIds)scheduleRecovery(cameraId,cause);}
function armRenew(productId){const player=players.get(productId);if(!player?.connection)return;clearTimeout(player.renew);const stream=player.connection.stream,remaining=Date.parse(stream.expiresAt)-Date.now(),delay=Math.max(0,remaining-Math.min(30000,remaining/3));player.renew=setTimeout(async()=>{try{const next=await call("renew_live_view",{sessionId,liveViewId:stream.liveViewId,viewerInstanceId});if(next.stream.streamProductId!==stream.streamProductId||next.stream.cameraId!==stream.cameraId)throw new Error("Renewed viewer product differs from active stream");player.connection=next;armRenew(productId);}catch(cause){await recoverProduct(productId,cause);}},delay);}
async function close(cameraId,remove,stopRecovery=true){if(stopRecovery)cancelRecovery(cameraId);const view=views.get(cameraId);views.delete(cameraId);const player=view?.productId?players.get(view.productId):null;if(player){player.views.delete(cameraId);if(!player.views.size){players.delete(view.productId);clearTimeout(player.renew);try{player.socket?.close(1000,"viewer closed");}catch(_){}player.admission?.close();if(player.connection){try{await call("close_live_view",{sessionId,liveViewId:player.connection.stream.liveViewId,viewerInstanceId});}catch(cause){if(!closing&&stopRecovery)error(cause);}}}}if(remove)$("view-"+cameraId)?.remove();if(!views.size&&!selected.size)$("grid").innerHTML='<div class="placeholder">Select a camera.</div>';status();reportSize();}
function renderChoices(){$("choices").replaceChildren(...cameras.map(camera=>{const label=document.createElement("label"),input=document.createElement("input");input.type="checkbox";input.checked=selected.has(camera.cameraId);input.disabled=camera.streamPolicy==="disabled";input.onchange=()=>{if(input.checked){selected.add(camera.cameraId);void open(camera);}else{selected.delete(camera.cameraId);void close(camera.cameraId,true);}};label.append(input,document.createTextNode(`${camera.cameraId} · ${camera.rig.kind} · ${camera.health} · ${smoothing(camera)}`));return label;}));reportSize();}
async function ensureSubscription(){if(!sessionId)return;const uri=`uav-sim://session/${sessionId}/live-cameras`;if(subscribedUri===uri)return;subscribedUri=uri;void bridge.request("subscriptions/listen",{notifications:{resourceSubscriptions:[uri]}}).catch(cause=>{if(!closing)error(cause);});}
async function discover(){const sessions=await read("uav-sim://sessions","sessions"),first=sessions[0];if(!first)throw new Error("No simulation is running. Start a simulation session, then reload this app.");sessionId=first.sessionId;$("session").textContent=`session ${sessionId}`;cameras=await call("list_live_cameras",{sessionId:sessionId});if(!selected.size)for(const camera of cameras)if(camera.streamPolicy!=="disabled")selected.add(camera.cameraId);await ensureSubscription();renderChoices();for(const camera of cameras)if(selected.has(camera.cameraId)&&!views.has(camera.cameraId))await open(camera);status();}
bridge.on("ui/notifications/resource-updated",params=>{const uri=params?.uri||params;if(typeof uri!=="string"||!sessionId||!uri.startsWith(`uav-sim://session/${sessionId}/live-`))return;void discover().then(()=>{if(uri.endsWith("/live-cameras"))retrySelectedNow();}).catch(error);});
function applyHostContext(context){const theme=context?.theme;if(theme==="light"||theme==="dark")document.documentElement.dataset.theme=theme;}
bridge.on("ui/notifications/host-context-changed",params=>applyHostContext(params?.hostContext||params));
bridge.on("ui/resource-teardown",(_params,id)=>{closing=true;for(const cameraId of recoveries.keys())cancelRecovery(cameraId);void Promise.all([...views.keys()].map(camera=>close(camera,true))).finally(()=>{if(id!==undefined)bridge.post({jsonrpc:"2.0",id,result:{}});});});
addEventListener("pagehide",()=>{closing=true;for(const player of players.values()){clearTimeout(player.renew);try{player.socket?.close();}catch(_){}player.admission?.close();}});
new ResizeObserver(reportSize).observe($("app"));
(async()=>{try{const initialized=await bridge.request("ui/initialize",{protocolVersion:"2026-01-26",appInfo:{name:"uav-sim-live",version:"3.0.0"},appCapabilities:{availableDisplayModes:["inline"]}});applyHostContext(initialized?.hostContext);configureAgents(initialized);bridge.notify("ui/notifications/initialized",{});await discover();reportSize();}catch(cause){error(cause);$("status").textContent="unavailable";}})();
