//! Public Media contracts without transport, Store or provider-client dependencies.
mod task_kind;
pub use task_kind::MediaTaskKind;
mod generation;
mod generation_result;
mod generation_uri;
mod prediction;
mod predictions;
mod subscriptions;
mod usage;
mod usage_metadata;
pub use generation::*;
pub use generation_result::*;
pub use generation_uri::*;
pub use prediction::*;
pub use predictions::*;
pub use subscriptions::*;
pub use usage::*;
pub use usage_metadata::*;

mod model;
pub use model::*;
mod resources;
pub use resources::*;
mod scopes;
pub use scopes::*;
mod artifact_uri;
pub use artifact_uri::*;
mod model_entry;
pub use model_entry::{ModelEntry, ModelResourceOutput};
mod model_catalog;
pub use model_catalog::*;
mod model_tools;
pub use model_tools::*;
mod requests;
pub use requests::*;
mod artifact_tools;
pub use artifact_tools::*;
