apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uav-sim
  namespace: flux-system
spec:
  interval: 5m
  timeout: 30m
  releaseName: uav-sim
  targetNamespace: veoveo
  storageNamespace: veoveo
  dependsOn:
    - name: veoveo
  chartRef:
    kind: OCIRepository
    name: uav-sim-chart-54c779b8864dda84639700fd5c949f845bbad027894746e8fef25302a84d35dd
  valuesFrom:
    - kind: ConfigMap
      name: bioma-uav-sim-values
      valuesKey: uav-sim-values.yaml
    - kind: ConfigMap
      name: bioma-uav-sim-values
      valuesKey: images.lock.yaml
  install:
    createNamespace: false
    serverSideApply: true
    remediation:
      retries: 5
  upgrade:
    serverSideApply: enabled
    remediation:
      retries: 5
      strategy: rollback
  driftDetection:
    mode: enabled
