use std::fmt;

/// Tables that may be used with the typed LIVE and changefeed helpers.
///
/// Keeping this closed prevents a caller-controlled identifier from being
/// interpolated into `LIVE SELECT` or `SHOW CHANGES` statements.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum PlatformTable {
    Enterprise,
    Tenant,
    Principal,
    Group,
    OauthClient,
    McpServer,
    Profile,
    PolicyRevision,
    GatewayControlRevision,
    GatewayControlObject,
    GatewayControlActive,
    GatewayResourceSubscription,
    GatewayJwtRevocation,
    GatewayReplayId,
    GatewayAuthorizationRequest,
    GatewayAuthorizationCode,
    GatewayRefreshFamily,
    GatewayRefreshToken,
    Task,
    TaskIdempotency,
    TaskInput,
    ProviderJob,
    ProviderEvent,
    ArtifactBlob,
    ArtifactOccurrence,
    ShareLink,
    ArtifactWriteCapability,
    ArtifactWriteRedemption,
    MediaTaskContext,
    MediaUsage,
    DomainUsage,
    Frame,
    CoordinateOperation,
    Recording,
    Segment,
    Agent,
    Wake,
    AgentEpisode,
    AgentTask,
    AgentElicitation,
    AuditEvent,
    OutboxEvent,
}

impl PlatformTable {
    pub const ALL: [Self; 42] = [
        Self::Enterprise,
        Self::Tenant,
        Self::Principal,
        Self::Group,
        Self::OauthClient,
        Self::McpServer,
        Self::Profile,
        Self::PolicyRevision,
        Self::GatewayControlRevision,
        Self::GatewayControlObject,
        Self::GatewayControlActive,
        Self::GatewayResourceSubscription,
        Self::GatewayJwtRevocation,
        Self::GatewayReplayId,
        Self::GatewayAuthorizationRequest,
        Self::GatewayAuthorizationCode,
        Self::GatewayRefreshFamily,
        Self::GatewayRefreshToken,
        Self::Task,
        Self::TaskIdempotency,
        Self::TaskInput,
        Self::ProviderJob,
        Self::ProviderEvent,
        Self::ArtifactBlob,
        Self::ArtifactOccurrence,
        Self::ShareLink,
        Self::ArtifactWriteCapability,
        Self::ArtifactWriteRedemption,
        Self::MediaTaskContext,
        Self::MediaUsage,
        Self::DomainUsage,
        Self::Frame,
        Self::CoordinateOperation,
        Self::Recording,
        Self::Segment,
        Self::Agent,
        Self::Wake,
        Self::AgentEpisode,
        Self::AgentTask,
        Self::AgentElicitation,
        Self::AuditEvent,
        Self::OutboxEvent,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Enterprise => "enterprise",
            Self::Tenant => "tenant",
            Self::Principal => "principal",
            Self::Group => "principal_group",
            Self::OauthClient => "oauth_client",
            Self::McpServer => "mcp_server",
            Self::Profile => "profile",
            Self::PolicyRevision => "policy_revision",
            Self::GatewayControlRevision => "gateway_control_revision",
            Self::GatewayControlObject => "gateway_control_object",
            Self::GatewayControlActive => "gateway_control_active",
            Self::GatewayResourceSubscription => "gateway_resource_subscription",
            Self::GatewayJwtRevocation => "gateway_jwt_revocation",
            Self::GatewayReplayId => "gateway_replay_id",
            Self::GatewayAuthorizationRequest => "gateway_authorization_request",
            Self::GatewayAuthorizationCode => "gateway_authorization_code",
            Self::GatewayRefreshFamily => "gateway_refresh_family",
            Self::GatewayRefreshToken => "gateway_refresh_token",
            Self::Task => "task",
            Self::TaskIdempotency => "task_idempotency",
            Self::TaskInput => "task_input",
            Self::ProviderJob => "provider_job",
            Self::ProviderEvent => "provider_event",
            Self::ArtifactBlob => "artifact_blob",
            Self::ArtifactOccurrence => "artifact_occurrence",
            Self::ShareLink => "share_link",
            Self::ArtifactWriteCapability => "artifact_write_capability",
            Self::ArtifactWriteRedemption => "artifact_write_redemption",
            Self::MediaTaskContext => "media_task_context",
            Self::MediaUsage => "media_usage",
            Self::DomainUsage => "domain_usage",
            Self::Frame => "frame",
            Self::CoordinateOperation => "coordinate_operation",
            Self::Recording => "recording",
            Self::Segment => "segment",
            Self::Agent => "agent",
            Self::Wake => "wake",
            Self::AgentEpisode => "agent_episode",
            Self::AgentTask => "agent_task",
            Self::AgentElicitation => "agent_elicitation",
            Self::AuditEvent => "audit_event",
            Self::OutboxEvent => "outbox_event",
        }
    }
}

impl fmt::Display for PlatformTable {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}
