//! Export selection and format agree before execution or capability reservation.
use super::{DuckDbDatabaseId, DuckDbSqlText, DuckDbTableName};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum DuckDbTabularFormat {
    Parquet,
    Csv,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(
    tag = "kind",
    rename_all = "snake_case",
    deny_unknown_fields,
    rename_all_fields = "camelCase"
)]
pub enum DuckDbTabularSelection {
    Table {
        table: DuckDbTableName,
    },
    /// Read-only SQL whose result set is exported.
    Sql {
        sql: DuckDbSqlText,
    },
}

/// A snapshot has its own format; row exports require a tabular format.
///
/// ```compile_fail
/// use veoveo_duckdb_mcp::contract::{DuckDbExportRequest, DuckDbTabularFormat};
/// let request = DuckDbExportRequest::Snapshot {
///     db: "metrics".parse().unwrap(),
///     format: DuckDbTabularFormat::Csv,
/// };
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(from = "ExportWire", into = "ExportWire")]
#[schemars(transform = object_schema)]
pub enum DuckDbExportRequest {
    Tabular {
        db: DuckDbDatabaseId,
        selection: DuckDbTabularSelection,
        format: DuckDbTabularFormat,
    },
    Snapshot {
        db: DuckDbDatabaseId,
    },
}

impl DuckDbExportRequest {
    pub fn database(&self) -> &DuckDbDatabaseId {
        match self {
            Self::Tabular { db, .. } | Self::Snapshot { db } => db,
        }
    }
}

// The public JSON keeps format beside selection. Each wire variant admits only
// selections that its format can represent. This is the single current format.
#[derive(Serialize, Deserialize, JsonSchema)]
#[serde(
    tag = "format",
    rename_all = "snake_case",
    deny_unknown_fields,
    rename_all_fields = "camelCase"
)]
enum ExportWire {
    Parquet {
        db: DuckDbDatabaseId,
        selection: DuckDbTabularSelection,
    },
    Csv {
        db: DuckDbDatabaseId,
        selection: DuckDbTabularSelection,
    },
    DuckDb {
        db: DuckDbDatabaseId,
        selection: SnapshotSelection,
    },
}

#[derive(Serialize, Deserialize, JsonSchema)]
#[serde(
    tag = "kind",
    rename_all = "snake_case",
    deny_unknown_fields,
    rename_all_fields = "camelCase"
)]
enum SnapshotSelection {
    Database {},
}

fn object_schema(schema: &mut schemars::Schema) {
    // Every ExportWire branch is an object. MCP requires that declaration at
    // the root as well as on the branches generated by the tagged enum.
    schema.insert("type".into(), "object".into());
}

impl From<ExportWire> for DuckDbExportRequest {
    fn from(value: ExportWire) -> Self {
        match value {
            ExportWire::Parquet { db, selection } => Self::Tabular {
                db,
                selection,
                format: DuckDbTabularFormat::Parquet,
            },
            ExportWire::Csv { db, selection } => Self::Tabular {
                db,
                selection,
                format: DuckDbTabularFormat::Csv,
            },
            ExportWire::DuckDb { db, .. } => Self::Snapshot { db },
        }
    }
}

impl From<DuckDbExportRequest> for ExportWire {
    fn from(value: DuckDbExportRequest) -> Self {
        match value {
            DuckDbExportRequest::Tabular {
                db,
                selection,
                format: DuckDbTabularFormat::Parquet,
            } => Self::Parquet { db, selection },
            DuckDbExportRequest::Tabular {
                db,
                selection,
                format: DuckDbTabularFormat::Csv,
            } => Self::Csv { db, selection },
            DuckDbExportRequest::Snapshot { db } => Self::DuckDb {
                db,
                selection: SnapshotSelection::Database {},
            },
        }
    }
}
