use std::fmt;
use veoveo_modules::{ChangefeedRetention, ObservationReplay, ObservationTable, TableName};

/// Kernel-owned observation tables.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum PlatformTable {
    KnowledgeCollection,
    KnowledgeGeneration,
    KnowledgeActive,
    KnowledgeMember,
    Enterprise,
    Tenant,
    Principal,
    Group,
    OauthClient,
    McpServer,
    Profile,
    PolicyRevision,
    GatewayControlRevision,
    GatewayControlObject,
    GatewayControlActive,
    GatewayResourceSubscription,
    GatewayJwtRevocation,
    GatewayReplayId,
    GatewayAuthorizationRequest,
    GatewayAuthorizationCode,
    GatewayRefreshFamily,
    GatewayRefreshToken,
    Task,
    TaskIdempotency,
    TaskInput,
    ProviderJob,
    ProviderEvent,
    ArtifactBlob,
    ArtifactOccurrence,
    ArtifactGrant,
    ShareLink,
    ArtifactWriteCapability,
    ArtifactReadCapability,
    ArtifactUpload,
    ArtifactUploadPart,
    ArtifactStorageUsage,
    ArtifactUploadMemory,
    ArtifactWriteRedemption,
    ArtifactAccessRequest,
    DomainUsage,
    AuditRecord,
    AuditBlock,
    WorkContext,
    KnowledgeSync,
    KnowledgeCoordinator,
}
impl PlatformTable {
    pub const ALL: [Self; 45] = [
        Self::KnowledgeCollection,
        Self::KnowledgeGeneration,
        Self::KnowledgeActive,
        Self::KnowledgeMember,
        Self::Enterprise,
        Self::Tenant,
        Self::Principal,
        Self::Group,
        Self::OauthClient,
        Self::McpServer,
        Self::Profile,
        Self::PolicyRevision,
        Self::GatewayControlRevision,
        Self::GatewayControlObject,
        Self::GatewayControlActive,
        Self::GatewayResourceSubscription,
        Self::GatewayJwtRevocation,
        Self::GatewayReplayId,
        Self::GatewayAuthorizationRequest,
        Self::GatewayAuthorizationCode,
        Self::GatewayRefreshFamily,
        Self::GatewayRefreshToken,
        Self::Task,
        Self::TaskIdempotency,
        Self::TaskInput,
        Self::ProviderJob,
        Self::ProviderEvent,
        Self::ArtifactBlob,
        Self::ArtifactOccurrence,
        Self::ArtifactGrant,
        Self::ShareLink,
        Self::ArtifactWriteCapability,
        Self::ArtifactReadCapability,
        Self::ArtifactUpload,
        Self::ArtifactUploadPart,
        Self::ArtifactStorageUsage,
        Self::ArtifactUploadMemory,
        Self::ArtifactWriteRedemption,
        Self::ArtifactAccessRequest,
        Self::DomainUsage,
        Self::AuditRecord,
        Self::AuditBlock,
        Self::WorkContext,
        Self::KnowledgeSync,
        Self::KnowledgeCoordinator,
    ];
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::KnowledgeCollection => "knowledge_collection",
            Self::KnowledgeGeneration => "knowledge_generation",
            Self::KnowledgeActive => "knowledge_active",
            Self::KnowledgeMember => "knowledge_member",
            Self::Enterprise => "enterprise",
            Self::Tenant => "tenant",
            Self::Principal => "principal",
            Self::Group => "principal_group",
            Self::OauthClient => "oauth_client",
            Self::McpServer => "mcp_server",
            Self::Profile => "profile",
            Self::PolicyRevision => "policy_revision",
            Self::GatewayControlRevision => "gateway_control_revision",
            Self::GatewayControlObject => "gateway_control_object",
            Self::GatewayControlActive => "gateway_control_active",
            Self::GatewayResourceSubscription => "gateway_resource_subscription",
            Self::GatewayJwtRevocation => "gateway_jwt_revocation",
            Self::GatewayReplayId => "gateway_replay_id",
            Self::GatewayAuthorizationRequest => "gateway_authorization_request",
            Self::GatewayAuthorizationCode => "gateway_authorization_code",
            Self::GatewayRefreshFamily => "gateway_refresh_family",
            Self::GatewayRefreshToken => "gateway_refresh_token",
            Self::Task => "task",
            Self::TaskIdempotency => "task_idempotency",
            Self::TaskInput => "task_input",
            Self::ProviderJob => "provider_job",
            Self::ProviderEvent => "provider_event",
            Self::ArtifactBlob => "artifact_blob",
            Self::ArtifactOccurrence => "artifact_occurrence",
            Self::ArtifactGrant => "artifact_grant",
            Self::ShareLink => "share_link",
            Self::ArtifactWriteCapability => "artifact_write_capability",
            Self::ArtifactReadCapability => "artifact_read_capability",
            Self::ArtifactUpload => "artifact_upload",
            Self::ArtifactUploadPart => "artifact_upload_part",
            Self::ArtifactStorageUsage => "artifact_storage_usage",
            Self::ArtifactUploadMemory => "artifact_upload_memory",
            Self::ArtifactWriteRedemption => "artifact_write_redemption",
            Self::ArtifactAccessRequest => "artifact_access_request",
            Self::DomainUsage => "domain_usage",
            Self::AuditRecord => "audit_record",
            Self::AuditBlock => "audit_block",
            Self::WorkContext => "work_context",
            Self::KnowledgeSync => "knowledge_sync",
            Self::KnowledgeCoordinator => "knowledge_coordinator",
        }
    }
}
impl From<PlatformTable> for ObservationTable {
    fn from(table: PlatformTable) -> Self {
        let replay = if table == PlatformTable::KnowledgeCoordinator {
            ObservationReplay::LiveOnly
        } else {
            ObservationReplay::Changefeed(
                ChangefeedRetention::from_days(7).expect("qualified kernel retention"),
            )
        };
        Self::new(
            TableName::new(table.as_str()).expect("kernel table declaration"),
            replay,
        )
    }
}
impl fmt::Display for PlatformTable {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}
