// DOM nodes are declared by the owner App template.
/** @param {string} id @param {string} tag */
function node(id,tag){const value=document.getElementById(id);if(!value||value.tagName.toLowerCase()!==tag)throw new Error(`Missing App element ${id}`);return value;}
const nodes={
 "access": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("access","div"))),
 "refresh": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("refresh","button"))),
 "save-view": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("save-view","button"))),
 "add-data": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("add-data","button"))),
 "status": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("status","div"))),
 "status-message": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("status-message","span"))),
 "live-updates": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("live-updates","span"))),
 "workspace": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("workspace","main"))),
 "visible-total": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("visible-total","span"))),
 "layer-search": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("layer-search","input"))),
 "authored-count": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("authored-count","span"))),
 "authored-list": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("authored-list","div"))),
 "source-section": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("source-section","section"))),
 "source-layer-count": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("source-layer-count","span"))),
 "source-layer-list": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("source-layer-list","div"))),
 "composition-count": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("composition-count","span"))),
 "composition-select": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("composition-select","select"))),
 "reset-view": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("reset-view","button"))),
 "map": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("map","div"))),
 "map-context-label": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("map-context-label","span"))),
 "viewport": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("viewport","span"))),
 "draw-tools": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("draw-tools","div"))),
 "draw-instruction": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("draw-instruction","span"))),
 "undo-drawing": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("undo-drawing","button"))),
 "finish-drawing": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("finish-drawing","button"))),
 "cancel-drawing": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("cancel-drawing","button"))),
 "gpu-badge": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("gpu-badge","div"))),
 "map-failure": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("map-failure","div"))),
 "inspector-title": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("inspector-title","h2"))),
 "close-action": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("close-action","button"))),
 "inspector-body": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("inspector-body","div"))),
 "preview": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("preview","section"))),
 "preview-title": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("preview-title","h2"))),
 "preview-count": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("preview-count","span"))),
 "preview-prev": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("preview-prev","button"))),
 "preview-page": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("preview-page","span"))),
 "preview-next": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("preview-next","button"))),
 "toggle-preview": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("toggle-preview","button"))),
 "preview-rows": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("preview-rows","tbody"))),
 "permission-note": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("permission-note","div"))),
 "action-picker-template": ()=> /** @type {HTMLTemplateElement} */ (/** @type {unknown} */ (node("action-picker-template","template"))),
 "create-layer-template": ()=> /** @type {HTMLTemplateElement} */ (/** @type {unknown} */ (node("create-layer-template","template"))),
 "create-layer-form": ()=> /** @type {HTMLFormElement} */ (/** @type {unknown} */ (node("create-layer-form","form"))),
 "new-layer-title": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("new-layer-title","input"))),
 "new-layer-description": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("new-layer-description","input"))),
 "new-layer-class": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("new-layer-class","select"))),
 "new-layer-schema": ()=> /** @type {HTMLTextAreaElement} */ (/** @type {unknown} */ (node("new-layer-schema","textarea"))),
 "new-layer-style": ()=> /** @type {HTMLTextAreaElement} */ (/** @type {unknown} */ (node("new-layer-style","textarea"))),
 "add-feature-template": ()=> /** @type {HTMLTemplateElement} */ (/** @type {unknown} */ (node("add-feature-template","template"))),
 "add-feature-form": ()=> /** @type {HTMLFormElement} */ (/** @type {unknown} */ (node("add-feature-form","form"))),
 "feature-layer": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("feature-layer","select"))),
 "feature-geometry-status": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("feature-geometry-status","div"))),
 "feature-title": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("feature-title","input"))),
 "feature-semantic-type": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("feature-semantic-type","input"))),
 "property-rows": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("property-rows","div"))),
 "add-property": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("add-property","button"))),
 "feature-json-advanced": ()=> /** @type {HTMLTextAreaElement} */ (/** @type {unknown} */ (node("feature-json-advanced","textarea"))),
 "apply-feature-json": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("apply-feature-json","button"))),
 "validate-feature": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("validate-feature","button"))),
 "feature-findings": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("feature-findings","div"))),
 "import-artifact-template": ()=> /** @type {HTMLTemplateElement} */ (/** @type {unknown} */ (node("import-artifact-template","template"))),
 "import-artifact-form": ()=> /** @type {HTMLFormElement} */ (/** @type {unknown} */ (node("import-artifact-form","form"))),
 "import-layer": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("import-layer","select"))),
 "import-artifact-id": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("import-artifact-id","input"))),
 "import-format": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("import-format","select"))),
 "import-semantic-type": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("import-semantic-type","input"))),
 "geopackage-fields": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("geopackage-fields","div"))),
 "inspect-geopackage": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("inspect-geopackage","button"))),
 "geopackage-table": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("geopackage-table","select"))),
 "geopackage-summary": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("geopackage-summary","div"))),
 "geopackage-identity": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("geopackage-identity","select"))),
 "geopackage-semantic": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("geopackage-semantic","select"))),
 "geopackage-title": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("geopackage-title","select"))),
 "import-progress": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("import-progress","div"))),
 "acquire-source-template": ()=> /** @type {HTMLTemplateElement} */ (/** @type {unknown} */ (node("acquire-source-template","template"))),
 "acquire-source-form": ()=> /** @type {HTMLFormElement} */ (/** @type {unknown} */ (node("acquire-source-form","form"))),
 "acquire-source": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("acquire-source","select"))),
 "draw-coverage": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("draw-coverage","button"))),
 "coverage-status": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("coverage-status","div"))),
 "bbox-west": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("bbox-west","input"))),
 "bbox-south": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("bbox-south","input"))),
 "bbox-east": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("bbox-east","input"))),
 "bbox-north": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("bbox-north","input"))),
 "save-view-template": ()=> /** @type {HTMLTemplateElement} */ (/** @type {unknown} */ (node("save-view-template","template"))),
 "save-view-form": ()=> /** @type {HTMLFormElement} */ (/** @type {unknown} */ (node("save-view-form","form"))),
 "save-view-title": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("save-view-title","input"))),
 "save-view-summary": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("save-view-summary","div"))),
 "raw-admin-template": ()=> /** @type {HTMLTemplateElement} */ (/** @type {unknown} */ (node("raw-admin-template","template"))),
 "raw-admin-form": ()=> /** @type {HTMLFormElement} */ (/** @type {unknown} */ (node("raw-admin-form","form"))),
 "raw-admin-title": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("raw-admin-title","h2"))),
 "raw-admin-json": ()=> /** @type {HTMLTextAreaElement} */ (/** @type {unknown} */ (node("raw-admin-json","textarea"))),
 "manage-data-template": ()=> /** @type {HTMLTemplateElement} */ (/** @type {unknown} */ (node("manage-data-template","template"))),
 "manage-acquisitions": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("manage-acquisitions","div"))),
 "manage-releases": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("manage-releases","div"))),
};
/** @template {string} K @param {K} id @returns {K extends keyof typeof nodes ? ReturnType<(typeof nodes)[K]> : HTMLElement} */
export function element(id){const get=Object.hasOwn(nodes,id)?nodes[/** @type {keyof typeof nodes} */ (id)]:undefined;const value=get?get():document.getElementById(id);if(!value)throw new Error(`Missing App element ${id}`);return /** @type {K extends keyof typeof nodes ? ReturnType<(typeof nodes)[K]> : HTMLElement} */ (value);}
/** @param {string} id @returns {HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement} */
export function input(id){const value=element(id);if(!(value instanceof HTMLInputElement||value instanceof HTMLSelectElement||value instanceof HTMLTextAreaElement))throw new Error(`Invalid App input ${id}`);return value;}

/** @template {keyof HTMLElementTagNameMap} T @param {ParentNode} root @param {string} selector @param {T} tag @returns {HTMLElementTagNameMap[T]} */
export function query(root,selector,tag){const value=root.querySelector(selector);if(!value||value.tagName.toLowerCase()!==tag)throw new Error(`Missing App element ${selector}`);return /** @type {HTMLElementTagNameMap[T]} */ (value);}
