{{- define "veoveo.modulePlan" -}}
{{- $raw := required "moduleInstallation.planJson must be generated by gateway module-plan" .Values.moduleInstallation.planJson -}}
{{- $plan := mustFromJson $raw -}}
{{- if ne $plan.format "veoveo.ai/module-plan/v1" }}{{ fail "unsupported module plan format" }}{{ end -}}
{{- if not (regexMatch "^sha256:[a-f0-9]{64}$" $plan.composition) }}{{ fail "module plan requires a composition digest" }}{{ end -}}
{{- if not (regexMatch "^[1-9][0-9]*$" $plan.generation) }}{{ fail "module plan requires a positive decimal-string installation generation" }}{{ end -}}
{{- if not $plan.credentialRevision }}{{ fail "module plan requires a credential revision" }}{{ end -}}
{{- $image := include "veoveo.ownedImage" (list . .Values.gateway.image) -}}
{{- if and .Values.global.production (not (hasSuffix (printf "@%s" $plan.composition) $image)) }}{{ fail "module plan composition differs from gateway image" }}{{ end -}}
{{- $components := include "veoveo.selectedComponents" . | fromYamlArray -}}
{{- $servers := include "veoveo.selectedMcpServers" . | fromYamlArray -}}
{{- $selected := dict -}}
{{- range $plan.lanes }}{{- $_ := set $selected .module true -}}{{ end -}}
{{- range $plan.runtimeBindings -}}
{{- $bound := or .component .mcpServer -}}
{{- $active := and $bound (or (not .component) (has .component $components)) (or (not .mcpServer) (has .mcpServer $servers)) -}}
{{- if and $active (not (hasKey $selected .module)) }}{{ fail (printf "enabled runtime requires selected module %s" .module) }}{{ end -}}
{{- end -}}
{{- toJson $plan -}}
{{- end -}}

{{- define "veoveo.modulePlanName" -}}
{{- $revision := .Values.moduleInstallation.planJson | sha256sum -}}
{{- include "veoveo.revisionedJobName" (list . "module-plan" $revision) -}}
{{- end -}}

{{- define "veoveo.modulePlanEnv" -}}
{{- $plan := include "veoveo.modulePlan" . | fromJson -}}
- name: VEOVEO_MODULE_PLAN
  value: /etc/veoveo/modules/plan.json
- name: VEOVEO_MODULE_COMPOSITION
  value: {{ $plan.composition | quote }}
- name: VEOVEO_INSTALLATION_GENERATION
  value: {{ $plan.generation | quote }}
- name: VEOVEO_CREDENTIAL_REVISION
  value: {{ $plan.credentialRevision | quote }}
- name: VEOVEO_SURREAL_RUNTIME_USERNAME
  valueFrom:
    secretKeyRef:
      name: {{ .Values.surrealdb.runtimeExistingSecret }}
      key: username
{{- end -}}

{{- define "veoveo.databasePodAnnotations" -}}
{{- if include "veoveo.componentEnabled" (list . "gateway") -}}
{{- $plan := include "veoveo.modulePlan" . | fromJson -}}
veoveo.ai/database-credential-revision: {{ $plan.credentialRevision | quote }}
{{- end -}}
{{- end -}}

{{- define "veoveo.migrationEnv" -}}
- name: VEOVEO_SURREAL_ENDPOINT
  value: ws://surrealdb:8000
- name: VEOVEO_SURREAL_NAMESPACE
  value: {{ .Values.surrealdb.namespace | quote }}
- name: VEOVEO_SURREAL_DATABASE
  value: {{ .Values.surrealdb.database | quote }}
- name: VEOVEO_SURREAL_AUTH_LEVEL
  value: root
- name: VEOVEO_SURREAL_USERNAME
  valueFrom:
    secretKeyRef:
      name: {{ .Values.surrealdb.adminExistingSecret }}
      key: username
- name: VEOVEO_SURREAL_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Values.surrealdb.adminExistingSecret }}
      key: password
{{- end -}}
