import {element as $} from "./dom.js";
import {configValue,streamsProjection,projectionValue,verifyProjectionBytes} from "./contracts.js";
import {ownerContracts,successfulToolEnvelope,toolEnvelope,taskEnvelope,resourceEnvelope} from "./admission.js";
import schemas from "./generated/workbench.schema.json" with {type:"json"};
const admit=ownerContracts(schemas);
const config=configValue(__VEOVEO_APP_CONFIG__);
let nextId=1,activeResource=config.resources[0]?.uri||null,activeValue=null,closed=false,activeCursor=null,pageHistory=[],resourceGeneration=0;
const pending=new Map(),handlers=new Map(),post=message=>parent.postMessage(message,"*");
addEventListener("message",event=>{if(event.source!==parent)return;const message=event.data;if(!message||message.jsonrpc!=="2.0")return;if(message.id!==undefined&&(message.result!==undefined||message.error!==undefined)){const waiter=pending.get(message.id);if(!waiter)return;pending.delete(message.id);message.error?waiter.reject(new Error(message.error.message||"host error")):waiter.resolve(message.result);return}const handler=handlers.get(message.method);if(handler)handler(message.params,message.id)});
const bridge={request(method,params){const id=nextId++;post({jsonrpc:"2.0",id,method,params});return new Promise((resolve,reject)=>pending.set(id,{resolve,reject}))},notify(method,params){post({jsonrpc:"2.0",method,params})},on(method,handler){handlers.set(method,handler)}};
function structured(result){return result?.structuredContent??result?.structured_content??result}
function taskId(value){return value?.taskId}
function taskState(value){return value?.status}
function terminal(state){return ["completed","failed","cancelled"].includes(String(state||"").toLowerCase())}
function resultText(value){const normalized=structured(value);return JSON.stringify(normalized,null,2)}
function setStatus(text,kind=""){const node=$("status");node.textContent=text;node.className=`status ${kind}`}
function reportSize(){requestAnimationFrame(()=>bridge.notify("ui/notifications/size-changed",{height:Math.ceil(document.documentElement.scrollHeight)}))}
function applyTheme(context){const theme=context?.theme;document.documentElement.dataset.theme=theme==="light"?"light":"dark"}
async function read(uri){const result=resourceEnvelope(await bridge.request("resources/read",{uri})),content=result.contents.find(item=>item.uri===uri);if(!content)throw new Error(`${uri} returned no content`);if("text" in content && typeof content.text==="string"){try{return JSON.parse(content.text)}catch{return content.text}}return content}
function cursorPage(value){
 if(!value)return null;
 const items=Array.isArray(value.items)?value.items:Array.isArray(value.models)?value.models:null;
 if(!items)return null;
 if(Object.hasOwn(value,"limit")){
  return Number.isSafeInteger(value.limit)&&value.limit>0&&items.length<=value.limit&&(value.nextCursor===null||(typeof value.nextCursor==="string"&&value.nextCursor.length>0))?{next:value.nextCursor}:null;
 }
 return items.length<=100&&items.every(item=>item&&typeof item.uri==="string")&&(value.nextCursor===undefined||(typeof value.nextCursor==="string"&&value.nextCursor.length>0))?{next:value.nextCursor??null}:null;
}
function updatePager(loading=false){const paged=cursorPage(activeValue);$("pager").hidden=!paged&&!pageHistory.length&&!activeCursor;$("page-previous").disabled=loading||!pageHistory.length;$("page-next").disabled=loading||!paged||!paged.next;$("page-number").textContent=`Page ${pageHistory.length+1}`}
async function selectResource(resource,cursor=null,history=[]){const generation=++resourceGeneration;activeResource=resource.uri;activeCursor=cursor;pageHistory=history;updatePager(true);document.querySelectorAll(".resource").forEach(node=>node.classList.toggle("active",node instanceof HTMLElement && node.dataset.uri===resource.uri));$("resource-title").textContent=resource.label;$("payload").textContent="Loading…";setStatus("reading");let uri=resource.uri;try{if(cursor!==null){const next=new URL(uri);next.searchParams.set("cursor",cursor);uri=next.href}const value=await read(uri);if(generation!==resourceGeneration||closed)return;activeValue=value;$("payload").textContent=resultText(value);setStatus("ready","good")}catch(error){if(generation!==resourceGeneration||closed)return;$("payload").textContent=`${uri}\n\n${error.message}`;setStatus("resource unavailable","bad")}updatePager();reportSize()}
async function awaitTask(created,output){const id=taskId(created);if(!id)return created;let snapshot=created;for(let attempt=0;attempt<240;attempt++){snapshot=taskEnvelope(await bridge.request("tasks/get",{taskId:id}),id);output.textContent=`Task ${id}\n${resultText(snapshot)}`;if(terminal(taskState(snapshot))){if(snapshot.status!=="completed")throw new Error(snapshot.statusMessage||`Task ${snapshot.status}`);return toolEnvelope(snapshot.result);}await new Promise(resolve=>setTimeout(resolve,500))}throw new Error(`task ${id} did not finish within 120 seconds`)}
async function receivePort(port){return new Promise((resolve,reject)=>{port.onmessage=event=>event.data?.error?reject(new Error(event.data.error)):resolve(event.data);port.onmessageerror=()=>reject(new Error("projection stream transfer failed"));port.start()})}
async function inspectProjectionStream(handle,output,args){handle=projectionValue(handle,args);if(!handle||typeof handle.recordingId!=="string"||typeof handle.projectionId!=="string")throw new Error("projection tool returned an invalid handle");const transfer=await bridge.request("veoveo/recordings/projection-stream",{recordingId:handle.recordingId,projectionId:handle.projectionId});if(transfer?.transfer!=="message_port"||!transfer.port)throw new Error("projection host did not provide a stream port");const received=await receivePort(transfer.port),stream=received?.stream;if(!(stream instanceof ReadableStream))throw new Error("projection host did not transfer a ReadableStream");const reader=stream.getReader();let receivedBytes=0,first=[],chunks=[];for(;;){const {done,value}=await reader.read();if(done)break;if(!(value instanceof Uint8Array)){await reader.cancel();throw new Error("Projection stream has invalid chunks");}receivedBytes+=value.byteLength;if(receivedBytes>handle.result.byteLen){await reader.cancel();throw new Error("Projection stream exceeds admitted length");}chunks.push(value);for(const byte of value){if(first.length>=16)break;first.push(byte)}}if(receivedBytes!==received.byteLength)throw new Error(`projection stream length mismatch: ${receivedBytes} != ${received.byteLength}`);await verifyProjectionBytes(handle,chunks);const magic=first.map(value=>value.toString(16).padStart(2,"0")).join(" ");output.textContent+=`\n\nArrow stream transferred through the Console host\nBytes: ${receivedBytes}\nSHA-256: ${handle.result.payloadSha256}\nFirst 16 bytes: ${magic}`}
async function runTool(tool,textarea,output,button){button.disabled=true;output.classList.add("visible");output.textContent="Running…";setStatus(`running ${tool.name}`);try{const args=JSON.parse(textarea.value||"{}");const created=toolEnvelope(await bridge.request("tools/call",{name:tool.name,arguments:args}));const result=successfulToolEnvelope(await awaitTask(created,output));output.textContent=resultText(result);if(streamsProjection(config,tool.name))await inspectProjectionStream(structured(result),output,args);setStatus("ready","good");if(activeResource)await selectResource(config.resources.find(resource=>resource.uri===activeResource)||config.resources[0])}catch(error){output.textContent=error.message;setStatus("action failed","bad")}finally{button.disabled=false;reportSize()}}
function render(){document.title=config.title;$("title").textContent=config.title;$("subtitle").textContent=config.subtitle;const resources=$("resources");if(!config.resources.length)resources.innerHTML=`<div class="empty">${config.emptyMessage}</div>`;for(const resource of config.resources){const button=document.createElement("button");button.className="resource";button.dataset.uri=resource.uri;button.textContent=resource.label;button.onclick=()=>selectResource(resource);resources.append(button)}const tools=$("tools");if(!config.tools.length)tools.innerHTML=`<div class="muted">Read-only workspace</div>`;for(const tool of config.tools){const card=document.createElement("section");card.className="tool";const head=document.createElement("div");head.className="tool-head";const title=document.createElement("h3");title.textContent=tool.label;const run=document.createElement("button");run.className="primary";run.textContent="Run";const input=document.createElement("textarea");input.value=tool.argumentsJson;input.setAttribute("aria-label",`${tool.label} JSON input`);const output=document.createElement("pre");output.className="tool-output";run.onclick=()=>runTool(tool,input,output,run);head.append(title,run);card.append(head,input,output);tools.append(card)}reportSize()}
$("refresh").onclick=()=>{const resource=config.resources.find(item=>item.uri===activeResource)||config.resources[0];if(resource)selectResource(resource,activeCursor,pageHistory)};
$("page-next").onclick=()=>{const resource=config.resources.find(item=>item.uri===activeResource);const page=cursorPage(activeValue);if(resource&&page?.next)selectResource(resource,page.next,[...pageHistory,activeCursor])};
$("page-previous").onclick=()=>{const resource=config.resources.find(item=>item.uri===activeResource);if(resource&&pageHistory.length)selectResource(resource,pageHistory.at(-1),pageHistory.slice(0,-1))};
$("copy").onclick=async()=>{if(activeValue!==null)await navigator.clipboard.writeText(resultText(activeValue))};
bridge.on("ui/notifications/host-context-changed",params=>applyTheme(params?.hostContext||params));
bridge.on("ui/notifications/tool-result",params=>{const value=structured(toolEnvelope(params?.result||params));if(value!==undefined){resourceGeneration++;activeCursor=null;pageHistory=[];$("pager").hidden=true;activeValue=value;$("payload").textContent=resultText(value)}});
bridge.on("ui/notifications/resource-updated",params=>{const uri=params?.uri||params;if(uri===activeResource)$("refresh").click()});
bridge.on("ui/resource-teardown",(_params,id)=>{closed=true;resourceGeneration++;if(id!==undefined)post({jsonrpc:"2.0",id,result:{}})});
(async()=>{render();try{const initialized=await bridge.request("ui/initialize",{protocolVersion:"2026-01-26",appInfo:{name:config.appId,version:"1.0.0"},appCapabilities:{availableDisplayModes:["inline"]}});applyTheme(initialized?.hostContext);bridge.notify("ui/notifications/initialized",{});if(config.resources[0])await selectResource(config.resources[0]);const uris=config.resources.map(resource=>resource.uri);if(uris.length)bridge.request("subscriptions/listen",{notifications:{resourceSubscriptions:uris}}).catch(()=>{})}catch(error){if(!closed){setStatus("unavailable","bad");$("payload").textContent=`${config.emptyMessage}\n\n${error.message}`}}finally{reportSize()}})();
