import { createRequire } from "node:module";
import { compile } from "json-schema-to-typescript";

const require = createRequire(import.meta.url);
if (require("json-schema-to-typescript/package.json").version !== "16.0.0") {
  throw new Error("Client generation requires json-schema-to-typescript 16.0.0; run npm ci.");
}
const chunks = [];
for await (const chunk of process.stdin) chunks.push(chunk);
const schema = JSON.parse(Buffer.concat(chunks).toString("utf8"));
// TypeScript's empty interface admits every non-nullish value. Render a closed
// empty JSON object as a dictionary which admits no keys instead.
for (const definition of Object.values(schema.$defs ?? {})) {
  if (
    definition.type === "object" &&
    definition.additionalProperties === false &&
    Object.keys(definition.properties ?? {}).length === 0 &&
    !definition.anyOf &&
    !definition.oneOf &&
    !definition.allOf
  ) {
    definition.tsType = "Record<string, never>";
  }
}
process.stdout.write(
  await compile(schema, schema.title, {
    bannerComment:
      "/* Generated by cargo xtask release client-types. Edit the owning Rust contract. */",
    additionalProperties: false,
    unreachableDefinitions: true,
    style: { singleQuote: false, printWidth: 100 },
  }),
);
