apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bioma-uav-sim
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bioma
  sources:
    - repoURL: charts-registry.argocd.svc.cluster.local/charts
      chart: uav-sim
      targetRevision: 0.1.0-612a7e411d63
      helm:
        releaseName: uav-sim
        valueFiles:
          - $configuration/examples/bioma/uav-sim-values.yaml
          - $configuration/examples/bioma/images.lock.yaml
    - repoURL: https://github.com/BiomaAI/veoveo.git
      targetRevision: 9c9656ac7513b747bf2adb3ff9ef6f1b1220e6ed
      ref: configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: veoveo
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
