// DOM nodes are declared by the owner App template.
/** @param {string} id @param {string} tag */
function node(id,tag){const value=document.getElementById(id);if(!value||value.tagName.toLowerCase()!==tag)throw new Error(`Missing App element ${id}`);return value;}
const nodes={
 "boot": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("boot","div"))),
 "boot-error": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("boot-error","div"))),
 "app": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("app","div"))),
 "subtitle": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("subtitle","span"))),
 "layer-select": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("layer-select","select"))),
 "view-chip": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("view-chip","span"))),
 "panel": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("panel","aside"))),
 "mode-tabs": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("mode-tabs","nav"))),
 "fs-target": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("fs-target","fieldset"))),
 "target-lat": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("target-lat","input"))),
 "target-lon": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("target-lon","input"))),
 "target-alt": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("target-alt","input"))),
 "fs-orbit": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("fs-orbit","fieldset"))),
 "orbit-distance-slider": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("orbit-distance-slider","input"))),
 "orbit-distance": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("orbit-distance","input"))),
 "orbit-azimuth-slider": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("orbit-azimuth-slider","input"))),
 "orbit-azimuth": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("orbit-azimuth","input"))),
 "orbit-elevation-slider": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("orbit-elevation-slider","input"))),
 "orbit-elevation": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("orbit-elevation","input"))),
 "fs-eye": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("fs-eye","fieldset"))),
 "eye-lat": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("eye-lat","input"))),
 "eye-lon": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("eye-lon","input"))),
 "eye-alt": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("eye-alt","input"))),
 "fs-orientation": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("fs-orientation","fieldset"))),
 "pose-heading-slider": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("pose-heading-slider","input"))),
 "pose-heading": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("pose-heading","input"))),
 "pose-pitch-slider": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("pose-pitch-slider","input"))),
 "pose-pitch": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("pose-pitch","input"))),
 "pose-roll": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("pose-roll","input"))),
 "fov-slider": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("fov-slider","input"))),
 "fov": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("fov","input"))),
 "resolved": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("resolved","div"))),
 "cap-width": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("cap-width","input"))),
 "cap-height": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("cap-height","input"))),
 "cap-sse": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("cap-sse","input"))),
 "cap-deadline": ()=> /** @type {HTMLInputElement} */ (/** @type {unknown} */ (node("cap-deadline","input"))),
 "cap-encoding": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("cap-encoding","select"))),
 "cap-behavior": ()=> /** @type {HTMLSelectElement} */ (/** @type {unknown} */ (node("cap-behavior","select"))),
 "btn-create": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("btn-create","button"))),
 "btn-apply": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("btn-apply","button"))),
 "btn-capture": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("btn-capture","button"))),
 "btn-cancel": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("btn-cancel","button"))),
 "btn-refresh-scene": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("btn-refresh-scene","button"))),
 "btn-copy": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("btn-copy","button"))),
 "btn-close": ()=> /** @type {HTMLButtonElement} */ (/** @type {unknown} */ (node("btn-close","button"))),
 "presets-details": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("presets-details","details"))),
 "preset-list": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("preset-list","div"))),
 "camera-error": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("camera-error","div"))),
 "stage": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("stage","main"))),
 "stage-tabs": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("stage-tabs","nav"))),
 "scene-pane": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("scene-pane","section"))),
 "gl": ()=> /** @type {HTMLCanvasElement} */ (/** @type {unknown} */ (node("gl","canvas"))),
 "scene-hud": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("scene-hud","div"))),
 "tile-chip": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("tile-chip","span"))),
 "scene-hint": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("scene-hint","span"))),
 "scene-attribution": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("scene-attribution","div"))),
 "frame-pane": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("frame-pane","section"))),
 "frame-wrap": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("frame-wrap","div"))),
 "frame-empty": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("frame-empty","span"))),
 "frame-img": ()=> /** @type {HTMLImageElement} */ (/** @type {unknown} */ (node("frame-img","img"))),
 "frame-attribution": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("frame-attribution","div"))),
 "frame-meta": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("frame-meta","dl"))),
 "diagnostics": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("diagnostics","div"))),
 "status": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("status","div"))),
 "status-text": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("status-text","span"))),
 "action-error": ()=> /** @type {HTMLElement} */ (/** @type {unknown} */ (node("action-error","div"))),
};
/** @template {string} K @param {K} id @returns {K extends keyof typeof nodes ? ReturnType<(typeof nodes)[K]> : HTMLElement} */
export function element(id){const get=Object.hasOwn(nodes,id)?nodes[/** @type {keyof typeof nodes} */ (id)]:undefined;const value=get?get():document.getElementById(id);if(!value)throw new Error(`Missing App element ${id}`);return /** @type {K extends keyof typeof nodes ? ReturnType<(typeof nodes)[K]> : HTMLElement} */ (value);}
/** @param {string} id @returns {HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement} */
export function input(id){const value=element(id);if(!(value instanceof HTMLInputElement||value instanceof HTMLSelectElement||value instanceof HTMLTextAreaElement))throw new Error(`Invalid App input ${id}`);return value;}
