apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: uav-sim-chart
  namespace: flux-system
spec:
  interval: 5m
  timeout: 2m
  url: oci://charts-registry.flux-system.svc.cluster.local:5000/charts/uav-sim
  insecure: true
  ref:
    digest: sha256:b06203229fadaad7040b0f341e8f5557bffe1b2fa1c336e54d892eb1d3388794
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
