apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: uav-sim-chart
  namespace: flux-system
spec:
  interval: 5m
  timeout: 2m
  url: oci://charts-registry.flux-system.svc.cluster.local:5000/charts/uav-sim
  insecure: true
  ref:
    digest: sha256:a441d9a8a634d8e27c2a5f549077533a04c0d1d93ec9ffa2a8f31ff38986b9bb
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
