/* automatically generated by rust-bindgen 0.73.2 */

/*
 * Copyright 2009-2026 NVIDIA Corporation.  All rights reserved.
 *
 * NOTICE TO LICENSEE:
 *
 * This source code and/or documentation ("Licensed Deliverables") are
 * subject to NVIDIA intellectual property rights under U.S. and
 * international Copyright laws.
 *
 * These Licensed Deliverables contained herein is PROPRIETARY and
 * CONFIDENTIAL to NVIDIA and is being provided under the terms and
 * conditions of a form of NVIDIA software license agreement by and
 * between NVIDIA and Licensee ("License Agreement") or electronically
 * accepted by Licensee.  Notwithstanding any terms or conditions to
 * the contrary in the License Agreement, reproduction or disclosure
 * of the Licensed Deliverables to any third party without the express
 * written consent of NVIDIA is prohibited.
 *
 * NOTWITHSTANDING ANY TERMS OR CONDITIONS TO THE CONTRARY IN THE
 * LICENSE AGREEMENT, NVIDIA MAKES NO REPRESENTATION ABOUT THE
 * SUITABILITY OF THESE LICENSED DELIVERABLES FOR ANY PURPOSE.  IT IS
 * PROVIDED "AS IS" WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND.
 * NVIDIA DISCLAIMS ALL WARRANTIES WITH REGARD TO THESE LICENSED
 * DELIVERABLES, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY,
 * NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE.
 * NOTWITHSTANDING ANY TERMS OR CONDITIONS TO THE CONTRARY IN THE
 * LICENSE AGREEMENT, IN NO EVENT SHALL NVIDIA BE LIABLE FOR ANY
 * SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, OR ANY
 * DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS
 * ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
 * OF THESE LICENSED DELIVERABLES.
 *
 * U.S. Government End Users.  These Licensed Deliverables are a
 * "commercial item" as that term is defined at 48 C.F.R. 2.101 (OCT
 * 1995), consisting of "commercial computer software" and "commercial
 * computer software documentation" as such terms are used in 48
 * C.F.R. 12.212 (SEPT 1995) and is provided to the U.S. Government
 * only as a commercial end item.  Consistent with 48 C.F.R.12.212 and
 * 48 C.F.R. 227.7202-1 through 227.7202-4 (JUNE 1995), all
 * U.S. Government End Users acquire the Licensed Deliverables with
 * only those rights set forth herein.
 *
 * Any use of the Licensed Deliverables in individual and commercial
 * software must include, in the user documentation and internal
 * comments to the code, the above Disclaimer and U.S. Government End
 * Users Notice.
 */

pub const NVJPEG_VER_MAJOR: u32 = 13;
pub const NVJPEG_VER_MINOR: u32 = 2;
pub const NVJPEG_VER_PATCH: u32 = 1;
pub const NVJPEG_VER_BUILD: u32 = 68;
#[repr(C)]
#[derive(Debug)]
pub struct CUstream_st {
    _unused: [u8; 0],
}
pub type cudaStream_t = *mut CUstream_st;
pub const libraryPropertyType_t_MAJOR_VERSION: libraryPropertyType_t = 0;
pub const libraryPropertyType_t_MINOR_VERSION: libraryPropertyType_t = 1;
pub const libraryPropertyType_t_PATCH_LEVEL: libraryPropertyType_t = 2;
pub type libraryPropertyType_t = ::std::os::raw::c_uint;
pub use self::libraryPropertyType_t as libraryPropertyType;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nvjpegStatus_t {
    NVJPEG_STATUS_SUCCESS = 0,
    NVJPEG_STATUS_NOT_INITIALIZED = 1,
    NVJPEG_STATUS_INVALID_PARAMETER = 2,
    NVJPEG_STATUS_BAD_JPEG = 3,
    NVJPEG_STATUS_JPEG_NOT_SUPPORTED = 4,
    NVJPEG_STATUS_ALLOCATOR_FAILURE = 5,
    NVJPEG_STATUS_EXECUTION_FAILED = 6,
    NVJPEG_STATUS_ARCH_MISMATCH = 7,
    NVJPEG_STATUS_INTERNAL_ERROR = 8,
    NVJPEG_STATUS_IMPLEMENTATION_NOT_SUPPORTED = 9,
    NVJPEG_STATUS_INCOMPLETE_BITSTREAM = 10,
}
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nvjpegChromaSubsampling_t {
    NVJPEG_CSS_444 = 0,
    NVJPEG_CSS_422 = 1,
    NVJPEG_CSS_420 = 2,
    NVJPEG_CSS_440 = 3,
    NVJPEG_CSS_411 = 4,
    NVJPEG_CSS_410 = 5,
    NVJPEG_CSS_GRAY = 6,
    NVJPEG_CSS_410V = 7,
    NVJPEG_CSS_UNKNOWN = -1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nvjpegInputFormat_t {
    NVJPEG_INPUT_YUV = 1,
    NVJPEG_INPUT_RGB = 3,
    NVJPEG_INPUT_BGR = 4,
    NVJPEG_INPUT_RGBI = 5,
    NVJPEG_INPUT_BGRI = 6,
    NVJPEG_INPUT_NV12 = 8,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nvjpegEncBackend_t {
    NVJPEG_ENC_BACKEND_DEFAULT = 0,
    NVJPEG_ENC_BACKEND_GPU = 1,
    NVJPEG_ENC_BACKEND_HARDWARE = 2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nvjpegImage_t {
    pub channel: [*mut ::std::os::raw::c_uchar; 4usize],
    pub pitch: [usize; 4usize],
}
#[repr(C)]
#[derive(Debug)]
pub struct nvjpegHandle {
    _unused: [u8; 0],
}
pub type nvjpegHandle_t = *mut nvjpegHandle;
#[repr(C)]
#[derive(Debug)]
pub struct nvjpegEncoderState {
    _unused: [u8; 0],
}
pub type nvjpegEncoderState_t = *mut nvjpegEncoderState;
#[repr(C)]
#[derive(Debug)]
pub struct nvjpegEncoderParams {
    _unused: [u8; 0],
}
pub type nvjpegEncoderParams_t = *mut nvjpegEncoderParams;
pub struct Nvjpeg {
    __library: ::libloading::Library,
    pub nvjpegGetProperty: unsafe extern "C" fn(
        type_: libraryPropertyType,
        value: *mut ::std::os::raw::c_int,
    ) -> nvjpegStatus_t,
    pub nvjpegCreateSimple: unsafe extern "C" fn(handle: *mut nvjpegHandle_t) -> nvjpegStatus_t,
    pub nvjpegDestroy: unsafe extern "C" fn(handle: nvjpegHandle_t) -> nvjpegStatus_t,
    pub nvjpegEncoderStateCreateWithBackend: unsafe extern "C" fn(
        handle: nvjpegHandle_t,
        encoder_state: *mut nvjpegEncoderState_t,
        backend: nvjpegEncBackend_t,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t,
    pub nvjpegEncoderStateDestroy:
        unsafe extern "C" fn(encoder_state: nvjpegEncoderState_t) -> nvjpegStatus_t,
    pub nvjpegEncoderParamsCreate: unsafe extern "C" fn(
        handle: nvjpegHandle_t,
        encoder_params: *mut nvjpegEncoderParams_t,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t,
    pub nvjpegEncoderParamsDestroy:
        unsafe extern "C" fn(encoder_params: nvjpegEncoderParams_t) -> nvjpegStatus_t,
    pub nvjpegEncoderParamsSetQuality: unsafe extern "C" fn(
        encoder_params: nvjpegEncoderParams_t,
        quality: ::std::os::raw::c_int,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t,
    pub nvjpegEncoderParamsSetSamplingFactors: unsafe extern "C" fn(
        encoder_params: nvjpegEncoderParams_t,
        chroma_subsampling: nvjpegChromaSubsampling_t,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t,
    pub nvjpegEncodeImage: unsafe extern "C" fn(
        handle: nvjpegHandle_t,
        encoder_state: nvjpegEncoderState_t,
        encoder_params: nvjpegEncoderParams_t,
        source: *const nvjpegImage_t,
        input_format: nvjpegInputFormat_t,
        image_width: ::std::os::raw::c_int,
        image_height: ::std::os::raw::c_int,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t,
    pub nvjpegEncodeRetrieveBitstream: unsafe extern "C" fn(
        handle: nvjpegHandle_t,
        encoder_state: nvjpegEncoderState_t,
        data: *mut ::std::os::raw::c_uchar,
        length: *mut usize,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t,
}
impl Nvjpeg {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let path = path.as_ref();
        let library = unsafe { ::libloading::Library::new(path) }?;
        unsafe { Self::from_library(library) }
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let nvjpegGetProperty = unsafe { __library.get(b"nvjpegGetProperty\0") }.map(|sym| *sym)?;
        let nvjpegCreateSimple =
            unsafe { __library.get(b"nvjpegCreateSimple\0") }.map(|sym| *sym)?;
        let nvjpegDestroy = unsafe { __library.get(b"nvjpegDestroy\0") }.map(|sym| *sym)?;
        let nvjpegEncoderStateCreateWithBackend =
            unsafe { __library.get(b"nvjpegEncoderStateCreateWithBackend\0") }.map(|sym| *sym)?;
        let nvjpegEncoderStateDestroy =
            unsafe { __library.get(b"nvjpegEncoderStateDestroy\0") }.map(|sym| *sym)?;
        let nvjpegEncoderParamsCreate =
            unsafe { __library.get(b"nvjpegEncoderParamsCreate\0") }.map(|sym| *sym)?;
        let nvjpegEncoderParamsDestroy =
            unsafe { __library.get(b"nvjpegEncoderParamsDestroy\0") }.map(|sym| *sym)?;
        let nvjpegEncoderParamsSetQuality =
            unsafe { __library.get(b"nvjpegEncoderParamsSetQuality\0") }.map(|sym| *sym)?;
        let nvjpegEncoderParamsSetSamplingFactors =
            unsafe { __library.get(b"nvjpegEncoderParamsSetSamplingFactors\0") }.map(|sym| *sym)?;
        let nvjpegEncodeImage = unsafe { __library.get(b"nvjpegEncodeImage\0") }.map(|sym| *sym)?;
        let nvjpegEncodeRetrieveBitstream =
            unsafe { __library.get(b"nvjpegEncodeRetrieveBitstream\0") }.map(|sym| *sym)?;
        Ok(Nvjpeg {
            __library,
            nvjpegGetProperty,
            nvjpegCreateSimple,
            nvjpegDestroy,
            nvjpegEncoderStateCreateWithBackend,
            nvjpegEncoderStateDestroy,
            nvjpegEncoderParamsCreate,
            nvjpegEncoderParamsDestroy,
            nvjpegEncoderParamsSetQuality,
            nvjpegEncoderParamsSetSamplingFactors,
            nvjpegEncodeImage,
            nvjpegEncodeRetrieveBitstream,
        })
    }
    pub unsafe fn nvjpegGetProperty(
        &self,
        type_: libraryPropertyType,
        value: *mut ::std::os::raw::c_int,
    ) -> nvjpegStatus_t {
        unsafe { (self.nvjpegGetProperty)(type_, value) }
    }
    pub unsafe fn nvjpegCreateSimple(&self, handle: *mut nvjpegHandle_t) -> nvjpegStatus_t {
        unsafe { (self.nvjpegCreateSimple)(handle) }
    }
    pub unsafe fn nvjpegDestroy(&self, handle: nvjpegHandle_t) -> nvjpegStatus_t {
        unsafe { (self.nvjpegDestroy)(handle) }
    }
    pub unsafe fn nvjpegEncoderStateCreateWithBackend(
        &self,
        handle: nvjpegHandle_t,
        encoder_state: *mut nvjpegEncoderState_t,
        backend: nvjpegEncBackend_t,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t {
        unsafe {
            (self.nvjpegEncoderStateCreateWithBackend)(handle, encoder_state, backend, stream)
        }
    }
    pub unsafe fn nvjpegEncoderStateDestroy(
        &self,
        encoder_state: nvjpegEncoderState_t,
    ) -> nvjpegStatus_t {
        unsafe { (self.nvjpegEncoderStateDestroy)(encoder_state) }
    }
    pub unsafe fn nvjpegEncoderParamsCreate(
        &self,
        handle: nvjpegHandle_t,
        encoder_params: *mut nvjpegEncoderParams_t,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t {
        unsafe { (self.nvjpegEncoderParamsCreate)(handle, encoder_params, stream) }
    }
    pub unsafe fn nvjpegEncoderParamsDestroy(
        &self,
        encoder_params: nvjpegEncoderParams_t,
    ) -> nvjpegStatus_t {
        unsafe { (self.nvjpegEncoderParamsDestroy)(encoder_params) }
    }
    pub unsafe fn nvjpegEncoderParamsSetQuality(
        &self,
        encoder_params: nvjpegEncoderParams_t,
        quality: ::std::os::raw::c_int,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t {
        unsafe { (self.nvjpegEncoderParamsSetQuality)(encoder_params, quality, stream) }
    }
    pub unsafe fn nvjpegEncoderParamsSetSamplingFactors(
        &self,
        encoder_params: nvjpegEncoderParams_t,
        chroma_subsampling: nvjpegChromaSubsampling_t,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t {
        unsafe {
            (self.nvjpegEncoderParamsSetSamplingFactors)(encoder_params, chroma_subsampling, stream)
        }
    }
    pub unsafe fn nvjpegEncodeImage(
        &self,
        handle: nvjpegHandle_t,
        encoder_state: nvjpegEncoderState_t,
        encoder_params: nvjpegEncoderParams_t,
        source: *const nvjpegImage_t,
        input_format: nvjpegInputFormat_t,
        image_width: ::std::os::raw::c_int,
        image_height: ::std::os::raw::c_int,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t {
        unsafe {
            (self.nvjpegEncodeImage)(
                handle,
                encoder_state,
                encoder_params,
                source,
                input_format,
                image_width,
                image_height,
                stream,
            )
        }
    }
    pub unsafe fn nvjpegEncodeRetrieveBitstream(
        &self,
        handle: nvjpegHandle_t,
        encoder_state: nvjpegEncoderState_t,
        data: *mut ::std::os::raw::c_uchar,
        length: *mut usize,
        stream: cudaStream_t,
    ) -> nvjpegStatus_t {
        unsafe { (self.nvjpegEncodeRetrieveBitstream)(handle, encoder_state, data, length, stream) }
    }
}
