//! Shared input for native chart tests; produced by the real gateway composition.
use anyhow::Result;
use std::io::Write;
use veoveo_modules::ModulePlanDocument;

pub fn module_plan() -> Result<tempfile::NamedTempFile> {
    // This fixture is regenerated by gateway module-plan, not a test-owned catalog.
    let wire = include_str!("../../../fixtures/module-schema-consumer/module-plan.json");
    let _: ModulePlanDocument = serde_json::from_str(wire)?;
    let mut file = tempfile::NamedTempFile::new()?;
    file.write_all(wire.as_bytes())?;
    file.flush()?;
    Ok(file)
}
