//! Task-bound capability request/result values and redacted secrets.
use crate::*;
use chrono::{DateTime, Utc};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::{
    collections::BTreeSet,
    fmt,
    num::{NonZeroU32, NonZeroU64},
};
use veoveo_types::DataLabelId;
/// Stable caller-selected identity for one asynchronous artifact write.
///
/// Retrying a capability redemption with the same key returns the UUIDv7
/// occurrence reserved by the first successful attempt. Before any occurrence
/// is staged, a retry may rebind that reservation to regenerated bytes; after
/// staging or finalization, retries always return the original occurrence.
#[derive(Debug, Clone, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize, JsonSchema)]
#[serde(transparent)]
pub struct ArtifactWriteIdempotencyKey(String);

impl ArtifactWriteIdempotencyKey {
    pub fn new(value: impl Into<String>) -> Result<Self, ArtifactWireError> {
        let value = value.into();
        if value.is_empty()
            || value.len() > 256
            || value.chars().any(char::is_control)
            || value.trim() != value
        {
            return Err(ArtifactWireError::invalid(
                "artifact write idempotency key must be 1..=256 trimmed, non-control characters",
            ));
        }
        Ok(Self(value))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ArtifactWriteIdempotencyKey {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl<'de> Deserialize<'de> for ArtifactWriteIdempotencyKey {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        Self::new(String::deserialize(deserializer)?).map_err(serde::de::Error::custom)
    }
}

/// Opaque identity of an artifact-write capability issued by the artifact
/// service. This is not an artifact id or a gateway identity assertion.
/// Bearer secret returned once by the artifact service. The issuing artifact
/// service stores only a one-way hash; the authorized domain server retains
/// the secret with the task that needs it after asynchronous completion.
#[derive(Clone, PartialEq, Eq, Serialize, JsonSchema)]
#[serde(transparent)]
pub struct ArtifactWriteCapabilitySecret(String);

impl ArtifactWriteCapabilitySecret {
    pub fn new(value: impl Into<String>) -> Result<Self, ArtifactWireError> {
        let value = value.into();
        if value.len() < 32 || value.chars().any(char::is_whitespace) {
            return Err(ArtifactWireError::invalid(
                "artifact write capability secret must be at least 32 non-whitespace characters",
            ));
        }
        Ok(Self(value))
    }

    pub fn expose_secret(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for ArtifactWriteCapabilitySecret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("ArtifactWriteCapabilitySecret(<redacted>)")
    }
}

impl<'de> Deserialize<'de> for ArtifactWriteCapabilitySecret {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Self::new(value).map_err(serde::de::Error::custom)
    }
}

/// Request a capability while a live gateway identity is available. The
/// artifact service binds the caller principal, tenant, labels, profile, and
/// server from that verified identity; clients cannot assert them here.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct IssueArtifactWriteCapabilityRequest {
    pub task_id: ArtifactTaskId,
    #[schemars(with = "veoveo_types::ChronoUtcTimestampSchema")]
    pub expires_at: DateTime<Utc>,
    pub max_artifact_count: NonZeroU32,
    pub max_total_bytes: NonZeroU64,
    /// Labels every output must retain, in addition to Work Context policy.
    /// Issuance requires the caller's clearance to cover this narrowing scope.
    #[serde(default, skip_serializing_if = "BTreeSet::is_empty")]
    #[schemars(length(max = 256))]
    pub required_data_labels: BTreeSet<DataLabelId>,
}

/// One-time issuance response. `secret` is returned only here and is redacted
/// from Debug output.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct IssuedArtifactWriteCapability {
    pub capability_id: ArtifactWriteCapabilityId,
    pub secret: ArtifactWriteCapabilitySecret,
    pub task_id: ArtifactTaskId,
    #[schemars(with = "veoveo_types::ChronoUtcTimestampSchema")]
    pub expires_at: DateTime<Utc>,
}

impl fmt::Debug for IssuedArtifactWriteCapability {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("IssuedArtifactWriteCapability")
            .field("capability_id", &self.capability_id)
            .field("secret", &"<redacted>")
            .field("task_id", &self.task_id)
            .field("expires_at", &self.expires_at)
            .finish()
    }
}

/// Typed redemption request. The capability bearer secret travels in the
/// Authorization header and is intentionally absent from this serializable
/// request body/header shape.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RedeemArtifactWriteCapabilityRequest {
    pub capability_id: ArtifactWriteCapabilityId,
    pub task_id: ArtifactTaskId,
    pub idempotency_key: ArtifactWriteIdempotencyKey,
    pub artifact: PutArtifactRequest,
}

/// A capability cannot enumerate artifacts or invoke a non-read operation.
/// Distinct occurrences charge their full length once; retries remain bounded
/// by the same expiry, context version, current grants, and clearance ceiling.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct IssueArtifactReadCapabilityRequest {
    pub task_id: ArtifactTaskId,
    #[schemars(with = "veoveo_types::ChronoUtcTimestampSchema")]
    pub expires_at: DateTime<Utc>,
    pub max_artifact_count: NonZeroU32,
    pub max_total_bytes: NonZeroU64,
}

#[derive(Clone, PartialEq, Eq, Serialize, JsonSchema)]
#[serde(transparent)]
pub struct ArtifactReadCapabilitySecret(String);

impl ArtifactReadCapabilitySecret {
    pub fn new(value: impl Into<String>) -> Result<Self, ArtifactWireError> {
        let value = value.into();
        if value.len() < 32
            || value.len() > 256
            || !value
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
        {
            return Err(ArtifactWireError::invalid(
                "invalid artifact read capability secret",
            ));
        }
        Ok(Self(value))
    }

    pub fn expose_secret(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for ArtifactReadCapabilitySecret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("ArtifactReadCapabilitySecret(<redacted>)")
    }
}

impl<'de> Deserialize<'de> for ArtifactReadCapabilitySecret {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Self::new(String::deserialize(deserializer)?).map_err(serde::de::Error::custom)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct IssuedArtifactReadCapability {
    pub capability_id: ArtifactReadCapabilityId,
    pub secret: ArtifactReadCapabilitySecret,
    pub task_id: ArtifactTaskId,
    #[schemars(with = "veoveo_types::ChronoUtcTimestampSchema")]
    pub expires_at: DateTime<Utc>,
}

/// Current-only domain separator for retained Artifact write requests.
/// Admission provides no historical format or implicit default.
#[derive(Debug, Clone, Copy, PartialEq, Eq, veoveo_types::Vocabulary)]
#[schemars(transform = request_format_naming)]
pub enum ArtifactWriteRequestFormat {
    #[vocabulary(rename = "veoveo.ai/artifact-write-request/v2")]
    V2,
}

fn request_format_naming(schema: &mut schemars::Schema) {
    *schema = veoveo_types::scalar_schema(
        schema.clone(),
        veoveo_types::ScalarNaming::builtin(veoveo_types::ScalarGrammar::FormatTag),
    )
    .expect("Artifact request format is a declared scalar");
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn write_task_aliases_emit_canonical_identity_and_reject_non_rfc_variants() {
        let id = ArtifactTaskId::new();
        let canonical = id.to_string();
        for alias in [
            canonical.to_uppercase(),
            id.as_uuid().simple().to_string(),
            format!("urn:uuid:{canonical}"),
        ] {
            let mut value = serde_json::json!({"taskId":alias,"expiresAt":"2026-10-06T12:00:00Z","maxArtifactCount":1,"maxTotalBytes":16});
            let request: IssueArtifactWriteCapabilityRequest =
                serde_json::from_value(value.clone()).unwrap();
            assert_eq!(request.task_id, id);
            assert_eq!(serde_json::to_value(request).unwrap()["taskId"], canonical);
            let mut wrong_variant = *id.as_uuid().as_bytes();
            wrong_variant[8] &= 0x3f;
            value["taskId"] = serde_json::json!(uuid::Uuid::from_bytes(wrong_variant).to_string());
            assert!(serde_json::from_value::<IssueArtifactWriteCapabilityRequest>(value).is_err());
        }
    }
    #[test]
    fn scalar_decoders_preserve_safe_invalid_request_prefix_and_secret_redaction() {
        let secret = "private short secret";
        let error =
            serde_json::from_value::<ArtifactWriteCapabilitySecret>(serde_json::json!(secret))
                .unwrap_err()
                .to_string();
        assert!(error.starts_with("invalid request: "));
        assert!(!error.contains(secret));
        assert!(
            serde_json::from_value::<ArtifactReadCapabilitySecret>(serde_json::json!(secret))
                .unwrap_err()
                .to_string()
                .starts_with("invalid request: ")
        );
        assert!(
            serde_json::from_value::<ArtifactWriteIdempotencyKey>(serde_json::json!(" "))
                .unwrap_err()
                .to_string()
                .starts_with("invalid request: ")
        );
    }
}

#[cfg(test)]
mod request_format_tests {
    use super::ArtifactWriteRequestFormat;

    #[test]
    fn retained_request_format_is_current_only() {
        let format = ArtifactWriteRequestFormat::V2;
        assert_eq!(
            serde_json::to_value(format).unwrap(),
            "veoveo.ai/artifact-write-request/v2"
        );
        for invalid in [
            serde_json::Value::Null,
            serde_json::json!("veoveo.ai/artifact-write-request/v1"),
            serde_json::json!("v2"),
        ] {
            assert!(serde_json::from_value::<ArtifactWriteRequestFormat>(invalid).is_err());
        }
    }
}
