apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: veoveo-bioma
servers: 1
agents: 0
image: veoveo/k3s-gpu:v1.36.2-k3s1-cuda13.3.0
kubeAPI:
  hostIP: 127.0.0.1
ports:
  - port: 127.0.0.1:8781:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: veoveo-registry.localhost
    host: 127.0.0.1
    hostPort: "5001"
    image: docker.io/library/registry:3.1.1@sha256:1be55279f18a2fe1a74edf2664cac61c1bea305b7b4642dab412e7affdcb3e33
    volumes:
      - veoveo-bioma-registry:/var/lib/registry
env:
  - envVar: NVIDIA_VISIBLE_DEVICES=all
    nodeFilters:
      - server:*
  - envVar: NVIDIA_DRIVER_CAPABILITIES=graphics,compute,utility,video
    nodeFilters:
      - server:*
options:
  k3d:
    wait: true
    timeout: 180s
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    gpuRequest: all
