import {element as el} from "./dom.js";
import {resourceJson, structuredResult, toolEnvelope, taskEnvelope} from "../../../mcp/apps-extension/browser/admission.js";
import {admit, resourceValue, toolValue} from "./contracts.js";
"use strict";

const bridge=(()=>{let next=1;const pending=new Map(),handlers=new Map(),post=(message)=>parent.postMessage(message,"*");window.addEventListener("message",(event)=>{if(event.source!==parent)return;const message=event.data;if(!message||message.jsonrpc!=="2.0")return;if(message.id!==undefined&&(message.result!==undefined||message.error!==undefined)){const waiter=pending.get(message.id);if(!waiter)return;pending.delete(message.id);message.error?waiter.reject(new Error(message.error.message||"host error")):waiter.resolve(message.result);return;}const handler=handlers.get(message.method);if(handler)handler(message.params,message.id);});return{request:(method,params)=>new Promise((resolve,reject)=>{const id=next++;pending.set(id,{resolve,reject});post({jsonrpc:"2.0",id,method,params});}),notify:(method,params)=>post({jsonrpc:"2.0",method,params}),on:(method,handler)=>handlers.set(method,handler),post};})();
let sessions=/** @type {import("./generated/stream").AppContracts["session"][]} */ ([]),selected=/** @type {import("./generated/stream").AppContracts["session"]|null} */ (null),timer=null,lastHeight=0,tearingDown=false,decoder=null,decoderSession=null,decoderGeneration=0,lastSequence=-1,waitingForKeyframe=true,decodedFrames=0,refreshPromise=null,refreshAgain=false;
let pageCursor=null,pageHistory=[],nextPageCursor=null,pageGeneration=0,pageLoading=true,sessionsReady=false,startPending=false;
function structured(result){if(result&&(result.isError||result.is_error)){const content=Array.isArray(result.content)?result.content:[];throw new Error((content.find((item)=>item.type==="text")||{}).text||"The Stream server didn't complete that request. Try again.");}return result&&(result.structuredContent||result.structured_content)||result;}
/** @template {keyof import("./generated/stream").AppContracts} K @param {string} uri @param {K} root @returns {Promise<import("./generated/stream").AppContracts[K]>} */
async function readJson(uri,root){return resourceValue(uri,resourceJson(await bridge.request("resources/read",{uri}),uri),root);}

/** @template {keyof typeof import("./contracts.js").tools} N @param {N} name @param {Record<string,unknown>} args @returns {Promise<import("./generated/stream").AppContracts[(typeof import("./contracts.js").tools)[N]]>} */
async function tool(name,args){return toolValue(name,structuredResult(await bridge.request("tools/call",{name,arguments:args})),args);}
async function sessionProduct(output,expectedId){if(typeof output?.result_uri!=="string"||typeof expectedId!=="string")throw new Error("The Stream server returned an incomplete session result. Reload to try again.");const session=await readJson(output.result_uri,"session");if(session?.session_id!==expectedId||session?.session_uri!==output.result_uri)throw new Error("The Stream server returned a different session. Reload to try again.");return session;}
function error(cause){el("error").textContent=cause instanceof Error?cause.message:String(cause);el("error").hidden=false;}function clear(){el("error").hidden=true;}
function status(text,kind=""){el("status").textContent=text;el("status").className=`chip ${kind}`;}
function report(){requestAnimationFrame(()=>{const height=Math.ceil(document.documentElement.scrollHeight);if(Math.abs(height-lastHeight)<2)return;lastHeight=height;bridge.notify("ui/notifications/size-changed",{height});});}
function idOf(item){return item?.session_id??item?.sessionId??null;}function field(item,snake,camel){return item?.[snake]??item?.[camel];}
function updateSessionSelector(){const selector=el("sessions"),selectedId=idOf(selected);selector.replaceChildren(...sessions.map((item)=>new Option(`${item.pipeline_id} · ${item.lifecycle} · ${idOf(item).slice(-8)}`,idOf(item),false,idOf(item)===selectedId)));selector.disabled=sessions.length===0;}
function draw(results,preview={}){const canvas=el("overlay"),box=canvas.getBoundingClientRect(),scale=devicePixelRatio||1;canvas.width=Math.max(1,Math.round(box.width*scale));canvas.height=Math.max(1,Math.round(box.height*scale));const context=canvas.getContext("2d");context.clearRect(0,0,canvas.width,canvas.height);const frame=results.frames.at(-1),detections=frame?.detections||[],width=selected?.video?.width||640,height=selected?.video?.height||480,detectionColor=getComputedStyle(document.documentElement).getPropertyValue("--cyan").trim()||"#c2a15c";context.lineWidth=2*scale;context.font=`${12*scale}px ui-sans-serif`;context.strokeStyle=detectionColor;context.fillStyle=detectionColor;for(const item of detections){const x=item.bounds.x/width*canvas.width,y=item.bounds.y/height*canvas.height,w=item.bounds.width/width*canvas.width,h=item.bounds.height/height*canvas.height;context.strokeRect(x,y,w,h);context.fillText(`${item.label}${item.confidence==null?"":` ${Math.round(item.confidence*100)}%`}`,x+3*scale,Math.max(14*scale,y-4*scale));}el("objects").textContent=String(detections.length);const processed=field(results,"processed_frames","processedFrames")||0,received=field(preview,"received_video_frames","receivedVideoFrames")||0;el("frames").textContent=String(processed);el("dropped").textContent=String(field(results,"dropped_result_frames","droppedResultFrames")||0);const observed=field(frame,"observed_at","observedAt");canvas.dataset.observedAt=observed||"";if(observed){const age=Math.max(0,Date.now()-Date.parse(observed));el("freshness").textContent=`frame age ${age} ms`;}else el("freshness").textContent=received?"streaming":"frame age —";}
function bytes(value){const raw=atob(value),output=new Uint8Array(raw.length);for(let index=0;index<raw.length;index++)output[index]=raw.charCodeAt(index);return output;}
function closeDecoder(){const current=decoder;decoder=null;if(current){try{current.close();}catch(_){}}}
function resetDecoder(sessionId){decoderGeneration+=1;closeDecoder();decoderSession=sessionId;lastSequence=-1;waitingForKeyframe=true;decodedFrames=0;const canvas=el("video"),context=canvas.getContext("2d");canvas.dataset.decodedFrames="0";context.clearRect(0,0,canvas.width,canvas.height);}
function recoverDecoder(cause,generation){if(generation!==decoderGeneration)return;decoderGeneration+=1;closeDecoder();lastSequence=-1;waitingForKeyframe=true;error(cause);status("decoder recovering","warn");}
async function configureDecoder(preview){if(typeof VideoDecoder==="undefined")throw new Error("This browser can't decode H.264 video with WebCodecs. Use a current Chrome, Edge, or Safari.");const id=idOf(preview),generation=decoderGeneration,video=preview.video,bitrate=field(video,"expected_bitrate_bps","expectedBitrateBps"),framerate=field(video,"frame_rate","frameRate");const media=await navigator.mediaCapabilities.decodingInfo({type:"file",video:{contentType:`video/mp4; codecs="${video.codec}"`,width:video.width,height:video.height,bitrate,framerate}});if(!media.supported||!media.smooth)throw new Error("This browser can't play this H.264 video smoothly. Turn on hardware acceleration in your browser settings and reload.");const acceleration=media.powerEfficient?"prefer-hardware":"prefer-software",config=/** @type {VideoDecoderConfig} */ ({codec:video.codec,codedWidth:video.width,codedHeight:video.height,hardwareAcceleration:acceleration,optimizeForLatency:true});const support=await VideoDecoder.isConfigSupported(config);if(!support.supported)throw new Error(`This browser can't decode this video (H.264 ${video.codec}, ${acceleration}). Turn on hardware acceleration in your browser settings and reload.`);if(generation!==decoderGeneration||id!==decoderSession)return false;el("decode").textContent=media.powerEfficient?"hardware H.264 decode":"software H.264 decode";const canvas=el("video");canvas.width=video.width;canvas.height=video.height;canvas.dataset.codec=video.codec;canvas.dataset.sourceWidth=String(video.width);canvas.dataset.sourceHeight=String(video.height);canvas.dataset.expectedBitrateBps=String(bitrate);canvas.dataset.frameRate=String(framerate);canvas.dataset.hardwareAcceleration=acceleration;const next=new VideoDecoder({output:(frame)=>{try{if(generation!==decoderGeneration)return;canvas.getContext("2d").drawImage(frame,0,0,canvas.width,canvas.height);decodedFrames+=1;canvas.dataset.decodedFrames=String(decodedFrames);canvas.dataset.lastFrameAt=new Date().toISOString();el("empty").hidden=true;clear();status(selected?.lifecycle||"running",selected?.lifecycle==="running"?"live":"warn");}finally{frame.close();}},error:(cause)=>recoverDecoder(cause,generation)});if(generation!==decoderGeneration||id!==decoderSession){next.close();return false;}decoder=next;decoder.configure(config);return true;}
async function decodePreview(preview){const id=idOf(preview);if(decoderSession!==id)resetDecoder(id);if(!decoder&&!(await configureDecoder(preview)))return;const generation=decoderGeneration;for(const chunk of preview.chunks){if(chunk.sequence<=lastSequence)continue;if(lastSequence>=0&&chunk.sequence>lastSequence+1)waitingForKeyframe=true;if(waitingForKeyframe&&!chunk.keyframe)continue;try{decoder.decode(new EncodedVideoChunk({type:chunk.keyframe?"key":"delta",timestamp:chunk.timestamp_us,data:bytes(chunk.data_base64)}));lastSequence=chunk.sequence;waitingForKeyframe=false;}catch(cause){recoverDecoder(cause,generation);return;}}}
function updateStart(){el("start").disabled=!sessionsReady||pageLoading||startPending||!el("pipeline").value||sessions.some((item)=>item.lifecycle==="running"&&(item.pipeline_id)===el("pipeline").value);}
function updatePaging(){updateStart();el("page-newer").disabled=pageLoading||pageHistory.length===0;el("page-older").disabled=pageLoading||!nextPageCursor;el("page-status").textContent=`Page ${pageHistory.length+1}`;}
function showPage(cursor,history,selection=null){pageGeneration+=1;pageCursor=cursor;pageHistory=history;nextPageCursor=null;pageLoading=true;sessionsReady=false;selected=selection;sessions=[];updateSessionSelector();resetDecoder(null);el("empty").hidden=false;el("stop").disabled=true;updatePaging();return scheduleRefresh();}
async function refresh(){
  if(tearingDown)return;
  const generation=pageGeneration;
  try{
    const uri=pageCursor?`stream://sessions?cursor=${encodeURIComponent(pageCursor)}`:"stream://sessions";
    const page=await readJson(uri,"sessions");
    if(tearingDown||generation!==pageGeneration)return;
    sessions=page.sessions;sessionsReady=true;nextPageCursor=page.next_cursor||null;pageLoading=false;updatePaging();
    const selectedId=idOf(selected);
    selected=sessions.find((item)=>idOf(item)===selectedId)||sessions.find((item)=>item.lifecycle==="running")||sessions[0]||null;
    updateSessionSelector();
    if(!selected){resetDecoder(null);el("empty").hidden=false;el("stop").disabled=true;el("session").textContent="no session";status("waiting","warn");draw({frames:[]});return;}
    const id=idOf(selected),[results,preview]=await Promise.all([readJson(`stream://session/${id}/results`,"results"),readJson(`stream://session/${id}/preview`,"preview")]);
    if(tearingDown||generation!==pageGeneration||id!==idOf(selected))return;
    el("session").textContent=`${id} · ${selected.lifecycle}`;
    const ingress=selected.ingress;el("ingress").textContent=`${ingress.host}:${ingress.port} · RTP/H.264`;
    const route=field(selected,"recording_output","recordingOutput");el("recording").textContent=route?`recording ${route.lifecycle} · ${field(route,"forwarded_video_frames","forwardedVideoFrames")} frames`:"recording route off";
    el("stop").disabled=selected.lifecycle!=="running";status(selected.lifecycle,selected.lifecycle==="running"?"live":"warn");
    await decodePreview(preview);
    if(tearingDown||generation!==pageGeneration||id!==idOf(selected))return;
    draw(results,preview);
  }catch(cause){if(generation!==pageGeneration||tearingDown)return;pageLoading=false;sessionsReady=false;updatePaging();error(cause);status("unavailable","warn");}
}
function scheduleRefresh(){if(tearingDown)return Promise.resolve();if(refreshPromise){refreshAgain=true;return refreshPromise;}refreshPromise=(async()=>{do{refreshAgain=false;await refresh();}while(refreshAgain&&!tearingDown);})().finally(()=>{refreshPromise=null;});return refreshPromise;}
async function loadPipelines(){const pipelines=await readJson("stream://pipelines","pipelines");el("pipeline").replaceChildren(...pipelines.filter((item)=>item.supports_live_input).map((item)=>new Option(item.title,item.id)));}
el("pipeline").addEventListener("change",updateStart);
el("start").addEventListener("click",async()=>{if(el("start").disabled||startPending)return;startPending=true;updateStart();try{clear();const output=await tool("start_live_session",{pipeline_id:el("pipeline").value});await showPage(null,[],await sessionProduct(output,output.session_id));}catch(cause){error(cause);}finally{startPending=false;updateStart();}});
el("page-older").addEventListener("click",()=>{if(nextPageCursor&&!pageLoading)void showPage(nextPageCursor,[...pageHistory,pageCursor]);});
el("page-newer").addEventListener("click",()=>{if(pageHistory.length&&!pageLoading)void showPage(pageHistory.at(-1),pageHistory.slice(0,-1));});
el("sessions").addEventListener("change",()=>{selected=sessions.find((item)=>idOf(item)===el("sessions").value)||null;resetDecoder(idOf(selected));void scheduleRefresh();});
el("stop").addEventListener("click",async()=>{if(!selected)return;const sessionId=idOf(selected);try{clear();const output=await tool("stop_live_session",{session_id:sessionId}),session=await sessionProduct(output,sessionId);if(idOf(selected)===sessionId)selected=session;await scheduleRefresh();}catch(cause){error(cause);}});
function applyHostContext(context){if(context&&(context.theme==="light"||context.theme==="dark")){document.documentElement.dataset.theme=context.theme;if(selected)void scheduleRefresh();}}
bridge.on("ui/notifications/tool-result",()=>void scheduleRefresh());bridge.on("ui/notifications/host-context-changed",(params)=>applyHostContext(params?.hostContext||params));bridge.on("ui/resource-teardown",(_params,id)=>{tearingDown=true;clearInterval(timer);resetDecoder(null);if(id!==undefined)bridge.post({jsonrpc:"2.0",id,result:{}});});
new ResizeObserver(report).observe(el("app"));window.addEventListener("resize",()=>{report();void scheduleRefresh();});
(async()=>{try{const initialized=await bridge.request("ui/initialize",{protocolVersion:"2026-01-26",appInfo:{name:"stream-live",version:"1.0.0"},appCapabilities:{availableDisplayModes:["inline"]}});applyHostContext(initialized?.hostContext);bridge.notify("ui/notifications/initialized",{});if(!navigator.mediaCapabilities?.decodingInfo)throw new Error("This browser can't report whether it plays H.264 smoothly, so live video is off. Use a current Chrome, Edge, or Safari.");await loadPipelines();await scheduleRefresh();timer=setInterval(()=>void scheduleRefresh(),250);report();}catch(cause){error(cause);status("failed","warn");}})();
